graphhopper.sh

I just changed the the version of maven to 3.2.5 as 3.2.3 is no longer available und the listed address. If 3.2.3 is required amother host should be selected.

Maven version updated to 3.2.5

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

Allow highway=cycleway and sac_scale=hiking for every kind of bike.
Disallow sac_scale=mountain_hiking for every bike except for MTB.
Allow highway=* and sac_scale=hiking for every kind of bike, except for the racebike.

Tuning for bicycles classifications for the sac_scale tag:

---

android/app/pom.xml

Advance the compiler compliance level for the Android to the max permitted 1.7.
That way we'll be able to use any Java 7 language features, if needed.

Android Maven: compiler compliance level 1.7

---

core/src/main/java/com/graphhopper/util/InstructionList.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java
web/src/main/java/com/graphhopper/http/GraphHopperServlet.java

Peter I think that in GPX the timestamps should be in UTC with ISO 8601 representation and end with the 'Z' suffix.
http://www.topografix.com/gpx_manual.asp#time
And to conform with spec, probably it's not necessary to provide the timezone as parameter to the createGPX method.

GPX: fix timestamp representation

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

This change was triggered by a discussion on the mailing list , see https://lists.openstreetmap.org/pipermail/graphhopper/2015-May/001964.html .
Improve avoidance of ways with high maxspeed values for cars and control the avoidance with one car speed on AVOID_IF_POSSIBLE level and another speed limit for the REACH_DEST avoidance.
The AVOID_IF_POSSIBLE max car speed is now defined as 71 km/h for all bike types except for the racingbike.
The REACH_DEST max car speed is now defined as 81 km/h for all bike types except for the racingbike.
The AVOID_IF_POSSIBLE max car speed is defined as 81 km/h for the racingbike.
The REACH_DEST max car speed is defined as 101 km/h for the racingbike.

Improve avoidance of ways with high maxspeed values for cars

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

The preference should not decrease for the following case: `highway=track` and `maxspeed=100` . This was detected as feedback for the change at #414 on the https://lists.openstreetmap.org/pipermail/talk-de/2015-May/111195.html for highway=track.
According to taginfo there are indeed some ways tagged in this combination. 
-> Now we do not decrease the preference for this case and cases where the highway type is in the prefered highway type list.

Do not decrease preference for highway=track with maxSpeed >= avoidSpeedLimit

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

This change adds support for the tag [`class:bicycle'](http://wiki.openstreetmap.org/wiki/Class:bicycle)
The implementation uses the subtypes `touring`, `mtb` and `roadcycling`. 
See also #330.

Add support for class:bicycle

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/graphhopper/android/MainActivity.java

As users have posted in our [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/Br1UQiMDwkk), at GH Android Sample there isn't any Mapsforge cleanup on app exit.
This PR handles this.
Also since Mapsforge doesn't yet support hardware acceleration (we're working on that) I set it to false in manifest, along with updating the sdk versions.

Android Sample: perform cleanup on exit, improvements at manifest

---

core/src/main/java/com/graphhopper/GHRequest.java
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/util/FastestWeighting.java
core/src/main/java/com/graphhopper/routing/util/PriorityWeighting.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/util/AngleCalc.java
core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/GHRequestTest.java
core/src/test/java/com/graphhopper/GraphHopperIT.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/routing/QueryGraphTest.java
core/src/test/java/com/graphhopper/routing/util/FastestWeightingTest.java
core/src/test/java/com/graphhopper/util/AngleCalcTest.java
docs/core/routing.md
docs/web/api-doc.md
web/src/main/java/com/graphhopper/http/GHBaseServlet.java
web/src/main/java/com/graphhopper/http/GraphHopperServlet.java
web/src/test/java/com/graphhopper/http/GraphHopperServletIT.java

Directions

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
tools/src/main/java/com/graphhopper/tools/Measurement.java

If you want to save CH preparation time and can accept a lot slower queries (still faster than without CH) you can now specify e.g. `prepare.contracted-nodes=97` which then only does the preparation for 97% of the nodes. In my experimental setup this leads to a 20% faster preparation but only a CH boost of 4. Same for 99%: you get 8% faster preparation but only a speed up factor of 9

make shorter CH preparation public available

---

web/src/main/webapp/js/ghrequest.js

The elevation control in the web GUI does not show up. 8009563b0f7638459006fe6c306dcb579ad5203c was the reason. In `GHRequest.prototype.init = function (params)` parameter  `this.vehicle` was still used, although the assignment was removed. So this should be changed into 'params.vehicle'.
The same is true below in 'GHRequest.prototype.initVehicle = function (vehicle) {` where 'this.vehicle' needs to be replaced with 'vehicle'.

Elevation control didn't show up

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/AbstractFlagEncoderTest.java

According to http://wiki.openstreetmap.org/wiki/Key:duration there is no dd:hh:mm format, instead this format needs to be interpreted as hh:mm:ss
The modification also fixes issue #501

Fix parsing of duration tag for hh:mm:ss format.

---

docs/core/deploy.md
docs/index.md

Hi as Described in #593 and #603 I added some more information to the deployment guide.
Especially about GraphHopper API tokens and Geocoding.

Added Geocoding Information to Documentation

---

web/src/main/webapp/css/style.css
web/src/main/webapp/js/autocomplete.js
web/src/main/webapp/js/main-template.js
web/src/main/webapp/js/map.js

Unless you are looking at directions for a very short distance, say total distance about < 1 km (which is not common), moving the mouse on the elevation profile by just 1 pixel will never make only the 3rd decimal digit change. 2nd decimal digit changes too. Thus 3rd digit is not significant and can be removed.
I'm hesitating about 2nd digit. It could be removed too in most cases. With directions about > 10 km long, the 2 digit is not significant when mousing over the elevation profile.
- ForceAxisBounds = false is default anyway
- Keeping "yAxisMin: 0" alone is useless unless "forceAxisBounds = true"
- Add missing exports
- Remove trailing space

Change default precision from 1 m to 10 m for distance label

---

core/src/main/java/com/graphhopper/util/DistanceCalcEarth.java

~~As a seasonal bonus this should increase test coverage (`calcNormalizedDist` was previously not covered by tests).~~ 
🎁
Edit: turns out it was covered by tests that I had just not noticed yet.

Remove duplicated and unreachable code.

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

Bicycle related change: Compensate the loss of road type speed by increasing the priority preference in case that a low maxspeed tag limits the speed below the guessed road type speed. 
This change was triggered by issue #597 and #597. See discussion in #600.

Compensate loss of road type speed by low maxspeed values via increase of preference

---

web/src/main/webapp/css/style.css
web/src/main/webapp/js/config/tileLayers.js

This PR will move down vehicle icons 1 or 2 px down, so they are centered inside their button.
Use Mapbox retina tiles when possible. It’s commented out here. For people who register their own API token and uncomment.
Simplify subdomains of tiles URL. In Leaflet, value “abc” is already default for {s}.

Center vehicle icons vertically in buttons + minor JS code refactor

---

web/src/main/webapp/js/main-template.js

When browsing another copy of the world, left or right the central one, after right-clicking on the map to add start, end, or intermediate points, error like this one is displayed:
```
Cannot find point 0: 52.50452,373.351135
Cannot find point 1: 52.516639,373.428383
```
This PR will make all clicks with longitude -180 to +180 degrees.
Uses the [wrap()](http://leafletjs.com/reference.html#latlng-wrap) function from Leaflet.
It's not a complete solution to this issue, as the route is always drawn on the main copy of the world. However it is still an improvement:
* Error is gone
* After routing results success, map is automatically panned to the route anyway (in central copy of world), and brings you back to the main world

Wrap coordinates around dateline

---

core/src/main/java/com/graphhopper/reader/dem/SRTMProvider.java

I created a mirror for the SRTM data at http://srtm.motoroute.me/. I set that URL as the new default. See also #292

Updated SRTM Provider URL

---

docs/core/routing.md

doc/core/routing.md seems to be outdated as for example it says that the InstructionList can be obtained directly from the GHResponse. However, first one needs to call getBest() or getAll() to obtain a PathWrapper.

Update documentation for simple routing example now using PathWrapper

---

config-example.properties
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/AStar.java
core/src/main/java/com/graphhopper/routing/AStarBidirection.java
core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
core/src/main/java/com/graphhopper/routing/AbstractRoutingAlgorithm.java
core/src/main/java/com/graphhopper/routing/AlgorithmOptions.java
core/src/main/java/com/graphhopper/routing/AlternativeRoute.java
core/src/main/java/com/graphhopper/routing/Dijkstra.java
core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java
core/src/main/java/com/graphhopper/routing/RoundTripAltAlgorithm.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithm.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/test/java/com/graphhopper/GraphHopperIT.java
core/src/test/java/com/graphhopper/routing/AbstractRoutingAlgorithmTester.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java

This PR contains the ability to limit the number of visitedNodes that a non-ch RoutingAlgorithm visits.
This can be specified in the config and via an URL parameter.
Fixes #473

Feature maximum visited nodes

---

core/src/main/java/com/graphhopper/reader/dem/SRTMProvider.java

Since I renamed my motorcycle route planer to Kurviger I had to change the base URL to [Kurviger.de](https://kurviger.de/). The old url will be still valid for the foreseeable future.

Updated SRTM URL to kurviger.de

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/test/java/com/graphhopper/GraphHopperTest.java

Prevents the creation of an empty folder when loading a Graph from a non-existent path.
The directory is created in GraphHopper.load() at line 837:
`        GHDirectory dir = new GHDirectory(ghLocation, dataAccessType);`
The directory is created before it is checked if the graph loading was successful. Therefore we can not simply omit the mkdirs call if the graph loading failed unless there would be a possibility to create the storage without creating the directory).
Also GraphHopper.load() is not only used to load an existing graph, but also in GraphHopper.importOrLoad() to initialize the GHStorage etc. (the actual loading is done only later in Graphhopper.process() in this case). 
The solution in this pull request is the least invasive I could come up with.
I check for the existence of …

Issue #644

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/test/java/com/graphhopper/GraphHopperAPITest.java
core/src/test/java/com/graphhopper/GraphHopperTest.java

First commit throws exception when using non-existent path in GraphHopper.load(),
second commit adjusts error message as discussed here: [#700](https://github.com/graphhopper/graphhopper/pull/700)

Issue #644 / PR #700 follow-up

---

CONTRIBUTORS.md
core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/test/java/com/graphhopper/reader/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/util/Bike2WeightFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/resources/com/graphhopper/reader/test-osm7.xml
docs/core/create-new-flagencoder.md

This fixes the bug in #665. The work to find this was done in #703.
This bug could be reproduced also for `bike2` which is very strange as I've never seen this failing in 'real world'.
The important part now is to set the flags for both speeds explicitly via
```java
flags = handleSpeed(way, ferrySpeed, flags);
```
or in motorcycle encoder via setSpeed&setReverseSpeed.
This is explicitly mentioned now in the create-new-flagencoder.md guide but the whole process should be made easier later on too.

Reproducing & fixing reverse speed error

---

android/gradle.properties

After testing (also in Mapsforge), let's stay on the safe side with the default settings.
Users can always use custom settings via their profiles.

Gradle properties: use default settings

---

core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java

Currently we do not validate the start of a round trip. This can lead to an empty response. Caused by an exception:
```
java.lang.IllegalStateException: Do not call QueryGraph.lookup with invalid QueryResult
```
This PR validates the start point.

Validate the start of a roundtrip

---

config-example.properties

`config.properties` refers to a request hint that must be set to force the use of flexible mode.  The hint mentioned in the comment does not appear to be correct (does not work).  The correct hint should be `routing.ch.disable=true`

Hint change for Java API

---

.travis.yml
core/files/settings.xml
core/files/travis-build.sh
core/pom.xml
pom.xml
web/pom.xml

As discussed in  https://github.com/graphhopper/graphhopper/issues/803#issuecomment-249179426 this PR brings JDK 9 builds on Travis-CI and automatic deployment of snapshots to the central repository.
The latter needs to have the secure keys generated and added in the `.travis.yml` (there are some placeholders there now) so that after a succesful build of the master branch the snapshot artifacts are deployed.
This build no longer uses the `/core/files/travis-build.sh` not sure if that can be removed, it has some out-commented npm stuff.

Travis-CI build enhancements

---

graphhopper.sh

I am using docker to run graphhopper. This pull request adds a new argument to the graphhopper.sh.
Now one can create (not only) docker images with a prebuilt graphhopper jar which also contains the web module.

add buildweb argument to graphhopper.sh which builds the graphhopper jar with the web module

---

.travis.yml

Something changed in the Java apt packages making the upgrade of the Java 9 JDK package [wait for userinput](https://travis-ci.org/graphhopper/graphhopper/jobs/170577756#L433); now it will just use the package provided files and run along.

Make Java 9 JDK update on Travis-CI work

---

core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java

To allow use of `findNetworkEntriesSingleRegion` when extending `LocationIndexTree` to create different search algorithms than `findNetworkEntries`. Use cases are e.g. map-matching and custom implementations e.g. [here](https://github.com/graphhopper/map-matching/pull/67).

making findNetworkEntriesSingleRegion public

---

core/src/main/java/com/graphhopper/routing/weighting/GenericWeighting.java
core/src/test/java/com/graphhopper/routing/weighting/GenericWeightingTest.java

We introduced a small bug with the Generic weighting. When we pass a null Graph on initialization, we try to get the NodeAccess, which results in a null-pointer exception.

CH-Preparation of Generic Vehicle

---

core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

This change avoids copying the graph necessary for #912. Copying the graph changes nodes & edge ids which introduces problems when trying to include turn costs for CH. 
TODOs:
* Investigate if this is faster (it should)
* Investigate if ch routing is done

Avoid copying graph, switch to CH routing via request parameter

---

.jitpack.yml

JitPack, which is super-useful, [tries to](https://jitpack.io/#graphhopper/graphhopper) build GraphHopper with Java 7, because it guesses that from our parent-pom. It doesn't realise that the web submodule needs Java 8.
Let's help it by adding a ``.jitpack.yml``. Then it works.

Add .jitpack.yml

---

core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/storage/index/QueryResult.java

The javadoc changes reflect my learnings about Graphhopper internals when I was implementing graphhopper/map-matching#88.

Improve javadoc comments

---

.travis.yml
core/src/main/java/com/graphhopper/util/Helper.java
pom.xml

This should pass the JDK9 travis tests once we have JDK9-ea-152 there, see #701.
And regarding the Android part, see #933

Improve cleaning of memory mapped ByteBuffers for JDK9 EA and Android

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodedDoubleValue.java
core/src/main/java/com/graphhopper/routing/util/EncodedValue.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java

As discussed in #947 this PR tries to implement the same behavior for EncodedValue and EncodedDoubleValue. The results of the division will be rounded. Additionally, I used the checkValue the same way we use it in the EncodedDoubleValue, after multiplying it with the factor again.
As this might change the values retrieved from an EncodedValue, I increased the version of all Encoders using it (I hope I haven't missed one) and added a notice in the changelog.
I moved the maxValue/factor == Integer check to the super constructor in the EncodedValue, I think this makes sense for the EncodedValue as well, right?

Added rounding for Encoded Value

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java

Flag-Encoders must call init() as their last action in the constructor. Therefore any FlagEncoder that does not call init() must be abstract.

Make BikeCommonFlagEncoder abstract

---

core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java

This is for #993 ~and [map-matching 65](https://github.com/graphhopper/map-matching/issues/65). Comments:~
- ~no real logic changed excepted made maxIterations configurable (from hardcoded value of 2 in map-matching) and throws an error if maxIterations 'truncates' the radius (as discussed in map-matching 65).~ I've added some comments for tidy-ups (that can be made later).
- ~renamed to `findWithinRadius` to better reflect the method (as opposed to the somewhat misleading `findNClosest`).~
- copied tests over from map-matching ~and added one to check the error is thrown for maxIterations truncation.~
- #971 was (I think) prompted by map-matching requirements for XFirstSearchCheck. This is no longer the case, so I'm not sure if we can close #971?
- required by [map-matching …

moved LocationIndexMatch.findNClosest from map-matching to LocationIndexTree

---

core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java

Important Bugfix, when loading an already prepared graph with LM, the server blocked at: completionService.take(), as no thread is created if LM is already prepared.
I introduced this bug with #995. The problem is that when loading a graph with prepared Landmarks that we don't spawn a thread if they are already prepared. With CH we create a new thread.
A test for this scenario would be nice as well, but I wasn't sure where to add something like this?
BTW: This is #1000 🎉🎉🎉

Bug when loading prepared graph with LM

---

reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtFlagEncoder.java

Import of the GTFS for Switzerland works but a few problems occurred:
* https://github.com/conveyal/gtfs-lib/issues/40
* And the max validityId was too small (What is its purpose?)
* (query takes long but this is already known)

GTFS from Switzerland requires larger validityids

---

reader-osm/src/main/java/com/graphhopper/reader/osm/OSMInput.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMInputFile.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

On OSM-Saturday at FOSSGIS, I sketched a (GraphHopper-based) routing-plugin for JOSM. Not worth checking out yet, but directly reading the JOSM data model from memory and finding a route from the GUI works like a charm -- in about 120 lines of code.
This is the minimal set of changes I had to make to plug into GraphHopper's OSM-import to have it read the data structures I feed it from JOSM, instead of a file.
(Could be followed up by a refactoring where the PBF and the XML file readers are separated.)

Create hook for importing OSM elements from something else than a File.

---

web/src/main/java/com/graphhopper/http/GraphHopperServlet.java
web/src/test/java/com/graphhopper/http/GraphHopperServletIT.java

Currently, there is a bug, when you don't specify a point in the request, but specify a heading. This PR fixes this bug, by assuming that a request that does not contain any points is not a valid request at all. I think this is a valid assumption?

Fixed Exception for requesting a point=undefined with heading

---

core/pom.xml
core/src/test/java/com/graphhopper/util/InstructionListTest.java
pom.xml
web/pom.xml
web/src/main/java/com/graphhopper/http/ChangeGraphServlet.java
web/src/main/java/com/graphhopper/http/GHBaseServlet.java
web/src/main/java/com/graphhopper/http/GraphHopperServlet.java
web/src/main/java/com/graphhopper/http/GraphHopperServletModule.java
web/src/main/java/com/graphhopper/http/GraphHopperWeb.java
web/src/main/java/com/graphhopper/http/I18NServlet.java
web/src/main/java/com/graphhopper/http/InfoServlet.java
web/src/main/java/com/graphhopper/http/InvalidRequestServlet.java
web/src/main/java/com/graphhopper/http/NearestServlet.java
web/src/main/java/com/graphhopper/http/SimpleRouteSerializer.java
web/src/main/java/com/graphhopper/http/WebHelper.java
web/src/test/java/com/graphhopper/http/BaseServletTester.java
web/src/test/java/com/graphhopper/http/ChangeGraphServletIT.java
web/src/test/java/com/graphhopper/http/GraphHopperServletIT.java
web/src/test/java/com/graphhopper/http/GraphHopperServletWithEleIT.java
web/src/test/java/com/graphhopper/http/NearestServletIT.java
web/src/test/java/com/graphhopper/http/NearestServletWithEleIT.java

Replaces json.org with jackson. Basically 1:1, without making much use of its features yet.
This does _not_ mean we can't switch to Gson. On the contrary, those two are very similar, and at the moment it would be search+replace, I think.

switch from json.org to jackson - minimal version

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Update Android and Gradle tools to their latest versions.
(preparing for GraphHopper 0.9 release)

Update Android and Gradle tools

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

As discussed in the [forum](https://discuss.graphhopper.com/t/adding-a-new-way-type-to-foot/2223), GraphHopper does not use piers for foot routing.
Piers are important to consider, for example to access ferries. Usually ferries also allow transportation of bikes, so I allowed piers also for bicycles.

Allow Foot, Hike, and Bike to enter Piers.

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

Fixes #1116. 
I removed the parameters with individual ferry speeds for the method getFerrySpeed. The speeds are now stored in the AbstractFlagEncoder.
The FootFlagEncoder, however, does not not allow to store speeds > 10 km/h. So I changed the max speed for the FootFlagEncoder to 15 km/h (still 4 bits). If the stored speed speed equals 15 km/h I return 20 km/h for the speed instead. This is the short_trip_ferry_speed. 
I increased the versions for Foot, as well as HikeEncoder, not for the others, as I didn't change anything with the EncodedValues for the others.

Equal Ferry Speeds between Encoders

---

reader-osm/pom.xml

OpenStreetMap finally updated their osmosis with protobuf 3.4.0 support so we can use new 0.46 version to fix this issue:
https://discuss.graphhopper.com/t/graphopper-reader-and-protobuf-3/2251/11

Update Osmosis to 0.46 for protobuf 3 support

---

.codeclimate.yml

Ok, CodeClimate is weird. I think we have to merge the `.codeclimate.yml` into the master. Before that we cannot look at the [issues](https://codeclimate.com/github/graphhopper/graphhopper/issues), as the issue view is not PR related. Since this PR changes a lot, I think it's not possible to see the detailed code quality change. I tried to make sure that js files get excluded by excluding their directory + all .js files.
So I would propose to merge this PR and see what changes in the issue view and if this is useful or not.
BTW: Java is [new](https://codeclimate.com/changelog/59cd14d00893fb028f00173b) in code climate, so I am not sure how well it is already integrated into the platform.

Added a simple codeclimate.yml

---

.travis.yml
core/src/main/java/com/graphhopper/util/PointList.java
pom.xml

As mentioned in #1184 findbugs and checkstyle slow down the test execution. I therefore removed the from the verify maven phase. They are still executed on travis, so if we introduce a massive issue in a PR travis should fail and report about it.
BTW: Findbugs seems to have issues with the Java 9 build.

Don't run findbugs and checkstyle as default during the ITs

---

client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java

I wasn't sure if the hc-client already supports PathDetails, so I wrote a test that made sure it does.

Added PathDetails test for the client

---

core/src/main/java/com/graphhopper/util/Helper.java
core/src/main/java/com/graphhopper/util/InstructionList.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java

[Kurviger](https://kurviger.de/en) received a [bug report](https://groups.google.com/d/msg/kurviger/b4TdQQSzkT8/nTGrpmTwAQAJ) that there can be an issue with the GPX export if coordinates are close to 0. The default formatting of Java for values like `0.000123` is `1.23E-4` which makes sense for readability, but some programs like Garmin Basecamp have issues importing these numbers.
This PR fixes this issue. I tried to stay as close to the current behaviour of GH as possible, but removing the exponential notation. For coordinates like 15.0 it prints 15.0 but not just 15 or 15.000000. Also values like 0.1 are printed as 0.1.

Fixed Exponential Notation for GPX export

---

.codeclimate.yml

Currently code climate is marking this code
```
if (line == null)
throw new IllegalStateException("Cannot read line " + lineNo);
```
as checkstyle violation. We use this widely in GH, so I think this check is not for us :).
[Here](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.html) is the JavaDoc for this feature.

Disable checking for braces

---

core/src/main/java/com/graphhopper/util/InstructionList.java

When I try to build the current master on a system with German locale, I get the following test failures:
InstructionListTest.testCreateGPX:483->verifyGPX:517 Runtime org.xml.sax.SAXPa...
InstructionListTest.testCreateGPXIncludesRoundaboutExitNumber:409->verifyGPX:517 Runtime
InstructionListTest.testCreateGPXWithEle:443->verifyGPX:517 Runtime org.xml.sa...
InstructionListTest.testInstructionsWithTimeAndPlace:319->verifyGPX:517 Runtime
They are caused by this exception:
```
java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 30; cvc-datatype-valid.1.2.1: '12,0' ist kein gültiger Wert für 'decimal'.
at com.graphhopper.util.InstructionListTest.verifyGPX(InstructionListTest.java:517)
at com.graphhopper.util.InstructionListTest.testCreateGPXWithEle(Instructio …
```

fixes decimal format in createGPX for locales with comma as separator

---

core/src/main/java/com/graphhopper/util/FinishInstruction.java
core/src/main/java/com/graphhopper/util/Instruction.java
core/src/main/java/com/graphhopper/util/InstructionList.java
core/src/main/java/com/graphhopper/util/PathMerger.java
core/src/main/java/com/graphhopper/util/PathSimplification.java
core/src/main/java/com/graphhopper/util/PointList.java
core/src/main/java/com/graphhopper/util/ShallowImmutablePointList.java
core/src/main/java/com/graphhopper/util/ViaInstruction.java
core/src/test/java/com/graphhopper/util/PointListTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

This PR fixes #1216 and also addresses parts of #1138.
This PR removes the duplicated point at ViaInstructions. Due to that we could also improve the Instructions and added the `getLength` method to the Instruction, which makes the code easier to read and is a step towards making instructions more similar to PathDetails.

Remove duplicated points at ViaPoints and add getLength to Instructions

---

.codeclimate.yml

I removed two Checkstyle warnings, one for local variables that have to follow a certain naming scheme. This rule was triggered by variables like `g`, or `myURL`. The other rule is about String wrapping, if you do: "a" + var.toString it tells you to wrap the + to a new line, which makes no sense to me.

Improve Checkstyle Warnings / Code Climate

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java

get/setSkippedEdge1/2 did not really work so far, but was not used anywhere either.
Also see discussion in #1225.

Makes AllCHEdgesIteratorImpl read/write skipped edges to/from shortcuts DataAccess

---

core/src/main/java/com/graphhopper/PathWrapper.java
core/src/main/java/com/graphhopper/util/PathSimplification.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
web/src/test/java/com/graphhopper/http/GraphHopperServletIT.java

If you request a route with two points, with start and end being the same snapped_point, the resulting path has only one point and no edges.
This resulted in an exception:
```
java.lang.IllegalStateException: PathDetails time must not be empty
at com.graphhopper.PathWrapper.addPathDetails(PathWrapper.java:258)
```
This PR proposes a possible solution for this by allowing to set empty PathDetails in the PathWrapper.
Due to this change the resulting PathDetails will be empty:
```
details: {
average_speed: [ ]
},
```

Fix PathDetails exception for empty EdgeIdDs list

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

Fixes #1256.
For cars, this feature makes only sense if a speed factor < 5 is used, so I am not sure if it makes sense? See my comment in #1256.

Force min speed value for short ferries

---

client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java

Fixes #1233.
I added ascend, descend, weight, and description to the client-hc.
Because description only appears for alternative_route, I had to write a test for alternative_route as well, with ch.disabled. Not sure if we want this? I tried to create a very short route < 1km.

Added ascend, descend, weight, and description to the client-hc

---

.travis.yml
android/app/pom.xml
client-hc/pom.xml
client-hc/src/test/java/com/graphhopper/api/GraphHopperMatrixGoogleIT.java
core/files/settings.xml
core/pom.xml
pom.xml
reader-gtfs/pom.xml
reader-json/pom.xml
reader-osm/pom.xml
reader-shp/pom.xml
tools/pom.xml
web/pom.xml

This PR automatically creates maven releases if a commit is tagged and fixes #1285 :) ! A first test was already *automatically* released as 0.10.alphaX on maven central.
It also changes a bit our travis handling uses the default way to support jdk9 and removes our old stuff.
Tasks:

Improve release management

---

client-hc/src/main/java/com/graphhopper/api/model/GHGeocodingEntry.java
client-hc/src/test/java/com/graphhopper/api/GraphHopperGeocodingIT.java

As mentioned by @devemux86 in #1221 the geocoding of the client-hc misses the osm key. While inspecting the Geocoding result I also saw that the extent was also missing, so I added that as well.
BTW: The extent is not documented in the API and I think the format is a bit weird (similar to Photon though). Should we add documentation about this feature in the API doc?

Added Extent and OsmKey to Geocoding

---

.gitignore
config-example.yml
graphhopper.sh

And replaces #1244 
Let us also document the old vs. the new way of configuring something:
|old | new
|-----|--------
|export JETTY_PORT=8989| --port 8989
|export GH_FOREGROUND=false| -d

Adapt graphhopper script for dropwizard branch

---

core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java

- ``no`` is a reserved word in YAML, like ``false`` in JSON
- YAML allows string values without quotes, except for reserved words
- the schema for our ``graphhopper`` configuration block is ``Map<String,String>``, we have no typesafe config yet
- so ``no`` is parsed to ``false: Boolean``, and then stringified to ``"false": String``
Solution: Just interpret ``"false"`` the same way as ``"no"``. No need to do anything more general about this IMO, since the general thing we should do is move to a typed config.
Alternative: Not do this and tell users to write ``"no"`` or to not use YAML. But I think allowing a second reserved string ourselves doesn't hurt.

allow "false" in addition to "no", fixes #1337

---

web/src/main/resources/assets/css/leaflet.elevation-0.0.4.css

It was not showing up and in a wrong color, due to a bad `.leaflet-overlay-pane` selector in CSS, which was removed in https://github.com/MrMufflon/Leaflet.Elevation/commit/94a5d5ee7e0708e1ea2399c1a95c37ab0e18b316.
I delete also here the unused themes, and keep only the white-theme.
Demo currently at: https://gh.bikewm.com/

Fix missing vertical bar for elevation

---

docs/index.md
docs/isochrone/java.md
docs/web/api-doc.md

Signed-off-by: Will Cohen <willcohen@users.noreply.github.com>
Re #1237 and a first pass at documentation:
- Adds annotations to the process used in IsochroneServlet to docs/isochrone/java.md, replacing the request parameters with variables at the top. Is this the right approach? It seems like sticking as close as possible to what's actually being used on the backend is important.
- Describes the parameters for /isochrone in docs/web/api-doc.md, based on the [directions API docs](https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/directions/api/client/api/IsochroneApi.java).
- Does not currently have javadocs. The algorithm itself is taken from OTP, and the meat of the isochrone generation itself is spread among the multiple …

(WIP) Isochrone documentation

---

web-api/src/main/java/com/graphhopper/http/WebHelper.java
web-api/src/test/java/com/graphhopper/http/WebHelperTest.java

As discussed in https://github.com/graphhopper/graphhopper-navigation/issues/1, we should make the precision of the polyline encoding configureable. 
This PR adds the option to change the precision of the Polyline encoding to use for example a precision of `1e6` as used by OSRM/Mapbox.

Allow configuring the precision of the polyline encoding

---

core/src/main/java/com/graphhopper/routing/ch/Path4CH.java

In this PR the path unpacking code in Path4CH is simplified.
The simplification makes the code easier to understand (hopefully, for me at least) and makes it easier to adjust for the turn-cost supporting version of CH.
I could not measure any significant performance difference running several comparisons on the map for Germany.

Simplifies path unpacking code for CH.

---

api/src/main/java/com/graphhopper/util/PMap.java
api/src/test/java/com/graphhopper/util/PMapTest.java
core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/ch/CHParameters.java
core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java

Following the discussion in #1368 I have tried to improve the parameter handling for CH and made the following changes:
1. `CHAlgoFactoryDecorator` is no longer aware of which parameters are used for `PrepareContractionHierarchies` and `NodeBasedNodeContractor`, but instead passes on the `CmdArgs` it is given in its `init()` method to `PrepareContractionHierarchies`. I think this is an improvement, because the decorator is no longer 'polluted' by CH-specific parameters. There will be more parameters when we add edge-based CH and even right now there are some parameters that are simply hard-coded and can't be changed at all (like the weightings in `NodeBasedNodeContractor#calculatePriority`). On the other hand since I removed the setters (`setPreparationContractedNodes` etc.) there is no …

Makes parameters available to CH classes via PMap.

---

core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java

So far we could pass a `Weighting` into `PrepareContractionHierarchies`, but in reality it has to match the `Weighting` that is used by `CHGraphImpl` which is also passed in. Here I have therefore removed the `Weighting` parameter from the constructor. For example without this fix I was able to circumvent the `IllegalStateException` here: https://github.com/graphhopper/graphhopper/blob/5cb035ad85f67b70109756878bf6fd9b953b4f9c/core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java#L140
minor: I replaced some cases of `assertTrue(false)` with `fail()` and removed some explicit array creations (cases where arrays are passed into methods with varargs... parameter).

Removes Weighting from PrepareContractionHierarchies constructor.

---

core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/DAType.java
core/src/main/java/com/graphhopper/storage/GHDirectory.java
core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java

This PR makes the CH-query speed 7% faster (without instructions it is 12% faster) and CH-preparation will be 15% faster.
While working on the performance problem in #1447 I stumbled over the fact that we use RAMIntDataAccess for the BaseGraph+LocationIndexTree only, but not for the shortcuts (CHGraphImpl.java).
TODO:

Speed up query and preparation for CH

---

tools/pom.xml

The Import class is gone since dropwizard refactoring, so 
```bash
java -jar  ...-with-dependencies.jar
```
yields `ClassNotFoundException`.
I think it is still useful to have the jar with dependencies and changed the main class to Measurement.

Makes Measurement the default main in gh tools jar with dependencies.

---

core/src/main/java/com/graphhopper/routing/ch/AbstractNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java

`AbstractNodeContractor` uses a `DataAccess` to keep track of originalEdges that are used for node priority calculation during CH preprocessing. originalEdges are an implementation detail of the CH preprocessing and are only needed temporarily and never get flushed to disk. Therefore I think it is better to create the `DataAccess` inside `AbstractNodeContractor` as it is done here. This allows removing the dir parameter from the `PrepareContractionHierarchies` and `NodeContractor` constructors and thus decouples the algorithm code from the storage. In a next step I think it would be quite easy to replace `GraphHopperStorage` with the `Graph` interface such that it will be possible to run CH with any graph implementation implementing the `(CH)Graph` interface.

Removes dir parameter from PrepareContractionHierarchies constructor.

---

core/pom.xml
core/src/main/resources/com/graphhopper/gitinfo

Using the maven-git-comit-id-plugin this PR adds a `gitinfo` properties file that contains git commit/hash/branch information after the build, so one can check which commit was used on an existing jar.
The plugin's license is LGPL.
https://github.com/git-commit-id/maven-git-commit-id-plugin

Adds gitinfo properties file containing git hash used when building.

---

core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java

Its easy to forget setting `edge_based=true` at query time when only edge based CH is prepared.

Improves error message in case of forgotten/wrong edge_based=true/false parameter.

---

core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookup.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupArray.java
core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupArrayTest.java

With this PR it's possible to retrieve a SpatialRule from the Lookup using the id. This can be especially helpful when one wants to store the id in the graph and retrieve the SpatialRule from that id.
One thing to consider is that if you change the SpatialRules (add one or change the the order), this will fail. Currently, we don't save the version of the SpatialRuleLookup.

Allow to retrieve SpatialRule by Id

---

core/src/main/java/com/graphhopper/routing/PathBidirRef.java
core/src/main/java/com/graphhopper/routing/util/TurnCostEncoder.java
core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/util/PathMerger.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/PathBidirRefTest.java
core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java

Fixes two of the three issues mentioned in #1585.
Added some tests and did some cleanup in some tests, but the actual fixes are one-liners.

Fixes some issues with turn cost times.

---

core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java

Fixes #1593.
The problem is this:
Let's say there are edges like this: 0-1-2 with edge-ids 0:0-1 and 1:1-2 and a shortcut gets introduced from 0 to 2 (skipping 1) (with id 2). Then there is a virtual node (id 3) between 1 and 2 like this: 1-(3)-2 which will add some virtual edges 3:1-3 and 4:3-2. When we detect u-turns we compare the edge ids. So if we travel via the shortcut from 0 to 2 we arrive at 2 with the shortcut id 2, but to calculate the turn costs we use the 'origEdgeLast' (here this is the edge 1-2 with id 1). When we check if going to the virtual node 3 is a u-turn we used to check 1==4 which tells us it is no u-turn (when in reality it is). So instead of the virtual edge id 4 we have to use the original edge id 1 for the comparison.
An important case is also checking for a …

Fixes edge-based CH problem with u-turns at virtual edges, fixes #1593

---

core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
core/src/main/java/com/graphhopper/storage/ShortcutUnpacker.java
core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java

Partly in preparation to include turn cost times with edge-based CH (#1585) and easier testing shortcut unpacking is moved from Path4CH to a separate class.

Extracts new ShortcutUnpacker from Path4CH.

---

api/src/main/java/com/graphhopper/util/Helper.java
core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/PathBidirRef.java
core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/ch/EdgeBasedPathCH.java
core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/EdgeAccess.java
core/src/main/java/com/graphhopper/storage/Graph.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/storage/ShortcutUnpacker.java
core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphSupport.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/RealtimeFeed.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/WrapperGraph.java

This PR adjusts the path unpacking such that turn cost times are included (previously they were ignored) for edge-based CH, see #1585.

Implements correct time calculation for edge-based CH.

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

Fixes #1580 
(Prior to the fix, gh would absolutely refuse to path to waypoint 2)
```
Continue onto Bernastrasse, get off the bike
Keep left, get off the bike
Waypoint 1
Continue, get off the bike
Waypoint 2
Continue onto Helvetiaplatz, get off the bike
Turn left, get off the bike
Arrive at destination
```
---
The fix was relatively straightforward, not sure what much to say about it, just adding the correct definitions for highway=platform in foot and bike encoder classes.
Reading the documentation of [Tag:highway=platform](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dplatform) did illustrate that `public_transport=platform` will also probably have to be dealt with at some point.
I took the time to look at the test unit structure and think about improvements, since @karussell seemed …

Route pedestrians over highway=platform, define it as a pushing section for bikes. Unit testing considerations.

---

reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

This check exists at the top of the method already and immediately returns if it the way has less than 2 nodes.

Remove unnecessary check if way has at least two nodes

---

core/src/main/java/com/graphhopper/routing/PathBidirRef.java
core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/weighting/TurnWeightingTest.java

This PR fixes the last remaining issue in #1585. The time calculation did not include the default u-turn cost (used when `TraversalMode.EDGE_BASED_2DIR_UTURN` is enabled).
With this in place I think we are ready to finally clean up the u-turn traversal mode etc. in #1520 :)

Includes default u-turn cost in time calculation, fixes #1585.

---

core/src/main/java/com/graphhopper/routing/profiles/DecimalEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/IntEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/MaxHeight.java
core/src/main/java/com/graphhopper/routing/profiles/MaxSpeed.java
core/src/main/java/com/graphhopper/routing/profiles/MaxWeight.java
core/src/main/java/com/graphhopper/routing/profiles/MaxWidth.java
core/src/main/java/com/graphhopper/routing/profiles/SimpleBooleanEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/UnsignedIntEncodedValue.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/test/java/com/graphhopper/routing/profiles/BooleanEncodedValueTest.java
core/src/test/java/com/graphhopper/routing/profiles/DecimalEncodedValueTest.java
core/src/test/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactoryTest.java
core/src/test/java/com/graphhopper/routing/profiles/IntEncodedValueTest.java
core/src/test/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValueTest.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/PtFlagEncoder.java

Fixes #1619 via renaming.
Supporting negative values is doable but introduces further complexity and overhead in the EncodedValue classes which I wouldn't want to do. At least not now, as the most use cases what to store per edge should be positive.

rename implementations of IntEncodedValue and DecimalEncodedValue

---

core/src/main/java/com/graphhopper/reader/dem/EdgeElevationInterpolator.java
core/src/main/java/com/graphhopper/reader/dem/ElevationInterpolator.java
core/src/main/java/com/graphhopper/reader/dem/NodeElevationInterpolator.java
core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/main/java/com/graphhopper/util/BreadthFirstSearch.java
core/src/main/java/com/graphhopper/util/DepthFirstSearch.java
core/src/main/java/com/graphhopper/util/EngineWarmUp.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/main/java/com/graphhopper/util/XFirstSearch.java
core/src/test/java/com/graphhopper/util/BreadthFirstSearchTest.java
core/src/test/java/com/graphhopper/util/DepthFirstSearchTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java

Improve speed of elevation interpolation

---

web/package.json
web/src/main/resources/assets/js/map.js

This PR hides the heightgraph on small screens.
In general there are two options for hiding:
- css
- js
The benefit of the css solution would be that on some devices the heightgraph would show up, when you turn the screen. Right now you would have to recalculate the route.
The benefit of the js solution is that we can avoid unnecessary calculations, which might speed up the overall performance, especially on potentially less powerful devices and long routes.

Don't show the heightgraph on small screens

---

web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java

Fixes #1655
The PR fixes the issue of reading unknown properties, but this changes the ObjectMapper configuration. I don't expect any issues due to that though. WDYT?

Ignore unknown properties of spatial rules

---

core/src/main/java/com/graphhopper/routing/ch/EdgeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/WitnessPathSearcher.java
core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/EdgeAccess.java
core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMTurnRelation.java

Are there any situations where we use edge ids that are `<0` and are not `-1` ? I added a check in `isValid` and ran the tests and there were no such situations in the tests.

Replaces some == NO_EDGE comparisons with isValid calls.

---

pom.xml

I could not resolve version `3.12` and on maven central it looks like the correct version would be `3.12.0`. The plugin website mentions the same version. Previously I saw errors about not finding the plugin in the CI logs sometimes, probably this was the problem.
- maven central: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-pmd-plugin
- plugin website: https://maven.apache.org/plugins/maven-pmd-plugin

Fixes maven pmd plugin version.

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

This is supposed to be a minimal fix to #1698.
Instead of deriving an 'overall' default traversal mode for *all* encoders every request checks whether or not the selected encoder supports turn costs and selects the traversal mode based on this (in case no edge_based parameter is sent along with the request).
Fixes #1698, but also related to #1637 and #1702.

Do not consider turn cost support of other encoders when selecting traversal mode

---

core/src/main/java/com/graphhopper/routing/util/parsers/OSMTollParser.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMTollParserTest.java

This PR modifies the OSMTollParser to treat `toll:N2` and `toll:N3` as special cases of `toll:hgv`.
[Wikipedia](https://en.wikipedia.org/wiki/Large_goods_vehicle):
> A heavy goods vehicle (HGV), also large goods vehicle (LGV) or medium goods vehicle, is the European Union (EU) term for any truck with a gross combination mass (GCM) of over 3,500 kilograms (7,716 lb). Sub-category N2 is used for vehicles between 3,500 kilograms (7,716 lb) and 12,000 kilograms (26,455 lb) and N3 for all goods vehicles over 12,000 kilograms (26,455 lb) as defined in Directive 2001/116/EC.

Add support for hgv toll sub-categories

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

This fixes #1637 and is based on #1705.
When we are determining the traversal mode and when the `edge_based` parameter is missing, we check what CH preparations are there (instead of looking at the turn cost support of the *encoder* as for non-CH).
So with this change we do no longer need to set `edge_based=true` to get edge-based CH and instead edge-based CH is picked automatically if it was prepared (if not we fall back to node-based CH). If `edge_based` is set on the request its value is respected (and there will be an error if the specified preparation is missing).
Note that with this PR we now choose edge-based CH when there are node *and* edge-based CH preparations for the chosen weighting **and** the `edge_based` parameter was not set.

Choose edge-based CH if it was prepared and the `edge_based` parameter was not set

---

config-example.yml
core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/profiles/MaxAxleLoad.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMWeightExtractor.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMWeightExtractorTest.java

This adds another crucial tag for proper commercial vehicle routing. The `maxaxleload` tag describes how many tonnes a single axle is allowed to have in order for a truck to be able to pass an edge. Like #1711 this may greatly change the possible routes of a vehicle as it dictates if a bridge can or cannot be crossed.
I went with an UnsignedDecimalEncodedValue with 7 bits and a 0.5 factor which allows us to store values up to 64 tonnes with a 0.5 precision. This is fully covers ~97% of [all tagged values](https://taginfo.openstreetmap.org/keys/maxaxleload#values) without loosing information and is still good enough to only be off by max 200kg for cases like `3.8t`.

New MaxAxleLoadParser

---

api/src/main/java/com/graphhopper/util/Parameters.java
web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java

This PR adds a new parameter `turn_costs=true/false`. This does the exact same as `edge_based=true/false` at the moment but is supposed to be more user-friendly (users who want to enable turn costs (or at least OSM turn restrictions) most likely do not know (and should not need to know) about the routing algorithm being edge-based.
This is basically the minimum change that adds this parameter, but I am not really happy with it, see #1725.

WIP: Add new `turn_costs=true/false` routing parameter

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/test/java/com/graphhopper/util/GHUtilityTest.java

Fix #1732 by making `copyProperties` not copy over the node IDs from old to new edge. No tests fail if I just remove the the call to `writeEdge` entirely in that method, but I'm assuming the reverse handling needs to be in there for a reason.

Fix sort corrupting graph

---

core/src/main/java/com/graphhopper/routing/lm/LMApproximator.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
core/src/test/java/com/graphhopper/routing/weighting/BidirectionalRoutingTest.java

Minimal fix for the two failing tests in #1687.
The first was already discussed (missing setter for the 'fallback' approximator).
The second one was due to an incorrect treatment of "minned out" "delta" weights. See comment in code.

Landmark bugs

---

api/src/main/java/com/graphhopper/GHRequest.java
client-hc/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java
client-hc/src/main/java/com/graphhopper/api/GHMatrixBatchRequester.java
client-hc/src/main/java/com/graphhopper/api/GHMatrixSyncRequester.java
client-hc/src/main/java/com/graphhopper/api/GraphHopperMatrixWeb.java
client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
client-hc/src/main/java/com/graphhopper/api/GzipRequestInterceptor.java
client-hc/src/test/java/com/graphhopper/api/AbstractGraphHopperMatrixWebIntegrationTester.java
client-hc/src/test/java/com/graphhopper/api/GHMatrixSyncTest.java
client-hc/src/test/java/com/graphhopper/api/GraphHopperWebIT.java
docs/web/api-doc.md
tools/pom.xml
web-api/src/main/java/com/graphhopper/jackson/GHPointDeserializer.java
web-api/src/main/java/com/graphhopper/jackson/GHRequestMixIn.java
web-api/src/main/java/com/graphhopper/jackson/GraphHopperModule.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java

fixes #1689
With the new "curbsides" features the problems described in #1689 will be even worse and so I think we need this new option. I was surprised that it was possible with so few code lines (the actual feature is 50 lines!). Especially nice is the possibility to annotate classes like GHRequest without adding the annotation dependency to core via so called MixIn classes.
TODOs:

introduce new POST /route possibility

---

core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/ShortFastestWeighting.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

fixes #733
Basically it moves the priorityEncoder to the CarFlagEncoder and fills it with bad priority if e.g. `vehicle` or `motor_vehicle` tag is `destination`

destination support for car that doesn't modify the speed

---

api/src/main/java/com/graphhopper/util/PMap.java
core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
core/src/test/java/com/graphhopper/routing/ch/CHProfileSelectorTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

Fixes #1788 .
This PR reworks the CH profile selection logic and now also handles the cases where the weighting or the vehicle is missing. It now works like this: A request comes in with or without `vehicle,weighting,edge_based,u_turn_costs`. Missing values are treated as wildcards (match everything). This means that we do not need to specify anything on the request as long as there is only one possible match. When there are multiple matches we throw an error (with one exception, see in code). 
The CH profile selection got much simpler. The error responses are now more generic and maybe even more informative. For example if no CH profile matches the request we get:
```
Cannot find matching CH profile for your request.
requested:  fastest|*|edge_based=true|u_turn_costs=40
available: …
```

Select appropriate CH profile when no weighting or vehicle is given

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/storage/GraphStorage.java
core/src/test/java/com/graphhopper/GraphHopperAPITest.java
core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageForDataFlagEncoderTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageWithTurnCostsTest.java
core/src/test/java/com/graphhopper/storage/GraphStorageViaMMapTest.java

Related to #1792. Removing the segment size setters from `DataAccess` seems to be a bigger task. For my purposes its sufficient for now to get rid of it on the graphs.

Moves segment size setting of graphs into constructor

---

config-example.yml
core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/profiles/HazmatTunnel.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParser.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMHazmatTunnelParserTest.java

This is a followup PR for the discussion in #1711 which adds the ability to honor restrictions on the transport of hazardous goods through tunnels.
Changes so far:
- added support for alternative tagging schemas `hazmat:adr_tunnel_cat` and `hazmat:tunnel_cat`
- check for the presence of `tunnel=yes` when dealing with hazmat subtags like `hazmat:B` to avoid collisions with tags in [Finland](https://wiki.openstreetmap.org/wiki/Key:hazmat#Finland).
You can run the following overpass turbo query to visualize the ways with supported tag combinations:
```
[out:json][timeout:25];
// gather results
(
way["hazmat:tunnel_cat"];
way["hazmat:adr_tunnel_cat"];
way["hazmat:A"="no"]["tunnel"="yes"];
way["hazmat:B"="no"]["tunnel"="yes"];
way["hazmat:C"="no"]["tunnel"="yes"]; …
```

Add support for EU tunnel codes

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHProfileSelector.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java

minor improvement for #1790 to call Weighting.matches again. A disadvantage could be that Weighting.matches is now less strict.

make CHProfile selection pluggable

---

core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxHeightParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxLengthParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMaxWidthParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMValueExtractor.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMValueExtractorTest.java

I've modified OSMValueExtractor to return `Double.NaN` for invalid values instead of throwing exceptions. Having a control flow which doesn't rely on unchecked exceptions is one point and the overhead of creating the exceptions is the other one:
It's on par with the memory allocation of the pbf parsing logic only because it's gathering the stacktraces which we don't even use later on.
Note that `Double.parseDouble()` might still throw a `NumberFormatException` for some cases but i'm not sure if it's worth to add an extra test method before invoking it.

Avoid throwing NumberFormatException in the OSMValueExtractor

---

core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
core/src/main/java/com/graphhopper/storage/Directory.java
core/src/main/java/com/graphhopper/storage/GHDirectory.java

If we do not remove the backing files of the ElevationProvider we should still release them.
Should finally fix the issue mentioned in https://github.com/graphhopper/graphhopper/pull/1755#issuecomment-544409278

Close mmap for ElevationProvider if not removed

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/SpatialRuleParser.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/GraphHopperAPITest.java
core/src/test/java/com/graphhopper/reader/dem/EdgeElevationInterpolatorTest.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/SnapPreventionEdgeFilterTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/SpatialRuleParserTest.java
core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
core/src/test/java/com/graphhopper/routing/weighting/GenericWeightingTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageForDataFlagEncoderTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

This PR basically moves all the current intermediate code into the build method making the EncodingManager.Builder a real builder. It is no longer required to know the order in which the different parsers should be added.
And it adds some EncodedValues if not yet existing. This will make it easier to handle instruction calculation like #990. Certainly some EncodedValues should still stay optional but having road_class and max_speed is important for calculating the instructions of all different travel modes. 
This PR also removes the no longer necessary method GHUtility.addDefaultEncodedValues. 
Now, if elevation is enabled the elevation interpolation is done without further configuration, ie. some tests needed minor changes.

introduce required encoded values

---

core/src/main/java/com/graphhopper/reader/ReaderElement.java
core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/profiles/GetOffBike.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParser.java
core/src/main/java/com/graphhopper/util/PathMerger.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/main/java/com/graphhopper/util/details/PathDetailsFromEdges.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/MountainBikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParserTest.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java
core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/TripFromLabel.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
web-bundle/src/test/java/com/graphhopper/util/gpx/GpxFromInstructionsTest.java

This removes the method and also a bit the ability to customize such annotations, but if this is really needed we can introduce it later. (There will follow up channges where we add warnings for fords and tolls.)
When multiple bike vehicles are used, this change will also reduce bit usage by 8 bits as it does no longer store the way type and paved/unpaved boolean in a separate EncodedValue but relies on `RoadClass` and could rely on `Surface`.
It also introduces a "ford warning" in all cases, so that we can switch defaults to handle #236 later (not in this PR)

Remove FlagEncoder.getAnnotation

---

benchmark/benchmark.sh
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalOSMTagInspector.java
core/src/main/java/com/graphhopper/reader/osm/conditional/DateRange.java
core/src/main/java/com/graphhopper/reader/osm/conditional/DateRangeParser.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
core/src/test/java/com/graphhopper/reader/osm/conditional/DateRangeParserTest.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java

make day for conditional tag parsing configurable

---

web/src/main/resources/assets/css/style.css

This PR proposes two fine tunings to the web UI. I'm not sure whether this part should be covered by additional unit tests, and/or should be split.
A first commit uses plain CSS to put a number in front of each step in the routing (to be able to see the correspondence with the markers on the map).
~~A second commit adds a checkbox that, when checked, prevents the automatic-rezoom features that takes place when the user adds an intermediate destination (this feature is very annoying when fine tuning very long tracks).~~

Improve large route ui (show step number)

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/template/RoutingTemplate.java
core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java

It looks like `maxRetries` was intended to be used with round trip calculation. But its disabled anyway, so I removed it (in hope of reducing some (but not a lot) complexity in `GraphHopper`).

Remove unused maxRetries mechanism in GraphHopper#calcPaths

---

web/src/main/resources/assets/js/main-template.js

This PR prevents the automatic-rezoom features that takes place when the user adds an intermediate destination (which can be very annoying when fine tuning very-very long tracks).
It is a simplified version of the commit removed from https://github.com/graphhopper/graphhopper/pull/1856

Disable rezooming on intermediate point addition

---

web/src/main/resources/assets/css/style.css

Fixes the issue (firefox only feature) raised in the discussions about the PR that added step numbers in the web UI : https://github.com/graphhopper/graphhopper/pull/1856

Fix step numbering in non-firefox browsers

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LMProfile.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

Here we maintain a pair of a profile name and a `Weighting` (=`LMProfile`) instead of just the `Weighting` for every LM preparation. This will be used to select an LM preparation by name similar to `CHProfile`. For now simply use default names `AbstractWeighting.weightingToFileName` so everything should work as before.

Use LMProfile instead of just Weighting for Landmark preparations

---

core/src/test/java/com/graphhopper/GraphHopperAPITest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java

* make tests depend less on each other by removing class variables
* stop relying on default vehicle/weighting for requests
* stop relying on default CH weighting for preparation
* production code is still the same

Cleanup GraphHopper tests in preparation to profile parameter

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/test/java/com/graphhopper/GraphHopperAPITest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
core/src/test/java/com/graphhopper/routing/ch/CHPreparationHandlerTest.java
core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageLMTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
docs/core/routing.md
docs/web/api-doc.md
reader-gtfs/README.md
reader-gtfs/src/test/java/com/graphhopper/ExtendedRouteTypeIT.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java
tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
web/src/test/java/com/graphhopper/http/SpatialRulesTest.java
web/src/test/java/com/graphhopper/http/resources/ChangeGraphResourceTest.java
web/src/test/java/com/graphhopper/http/resources/GpxTravelTimeConsistencyTest.java
web/src/test/java/com/graphhopper/http/resources/I18nResourceTest.java
web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java
web/src/test/java/com/graphhopper/http/resources/MvtResourceTest.java
web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceWithEleTest.java
web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java

So far when creating a new `GraphHopper` instance the `CHPreparationHandler` was set to be enabled and `"fastest"` was used as default weighting, resulting in a `"fastest"` CH preparation for every vehicle. In this PR I have removed this default so there no longer are any CH preparations by default. I also removed the `LMPreparationHandler#setEnabled` methods, because there are only two cases: Either some CH/LM profiles are configured (then CH/LM is enabled) or not (then CH/LM is disabled), which means `setEnabled(false)` is equivalent to setting up no `CH/LMProfile`s and `setEnabled(true)` requires setting up the profiles and is thus unnecessary. 
The usage goes like this now:
```config.yml
graphhopper:
prepare.ch.weightings=fastest
prepare.lm.weightings=no
```
```java
// create a new …
```

No longer enable CH by default in GraphHopper class

---

api/pom.xml
client-hc/pom.xml
core/pom.xml
isochrone/pom.xml
pom.xml
reader-gtfs/pom.xml
reader-osm/pom.xml
tools/pom.xml
web-api/pom.xml
web-bundle/pom.xml
web/pom.xml

Fixes #1906. 
I moved most dependency versions into parent pom's dependency management section and move the junit 4 dependency there as well. For dropwizard I used their bom file.

Add dependency management and junit4 dependency to parent pom

---

client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
config-example.yml
core/files/changelog.txt
web-api/src/main/java/com/graphhopper/jackson/GHRequestMixIn.java
web-api/src/main/java/com/graphhopper/jackson/Jackson.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java

of GHRequest in GHRequestMixIn.
Unfortunately there seems to be no lowerCamelCase naming strategy. With such a strategy we could enable it globally and annotate only GraphHopperConfigMixIn (or should we create something like this?)

no need to explicitely list the snake case methods

---

core/src/main/java/com/graphhopper/routing/profiles/Country.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/SpatialRuleParser.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/CountriesSpatialRuleFactory.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelper.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupJTS.java
core/src/test/java/com/graphhopper/routing/util/parsers/SpatialRuleParserTest.java
core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelperTest.java
reader-osm/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
web/src/test/java/com/graphhopper/http/SpatialRulesTest.java

fixes #1875
As we currently already sort the strings https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilder.java#L86
the only required change for #1875 would be to reorder the Country enum (AUT should come before DEU).
But as this is too error-prone I decided for a better & special handling when using the Country enum in combination with the SpatialRuleFactory. This is currently done in SpatialRuleLookupHelper.buildAndInjectSpatialRuleIntoGH. I have renamed this to a more Country-specific name as it is nothing generic. ~~Also `spatial_rules.borders_directory` is renamed to `country.borders_directory` to make usage more clear~~. To avoid mixing this in the future I have removed the SpatialRuleParser …

fix country rule ordering

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/weighting/BlockAreaWeighting.java
core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java
core/src/test/java/com/graphhopper/storage/GraphEdgeIdFinderTest.java
core/src/test/java/com/graphhopper/storage/change/ChangeGraphHelperTest.java
core/src/test/resources/com/graphhopper/storage/change/overlaydata1.json
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java
web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java

This PR fixes #1324.
There were a couple of bugs with the block_area feature that are fixed within this PR:
* virtual edges are handled now, see #1127
* bread first search is replaced with locationIndex lookup, which avoids several problems documented in #1324
* edgeId cache is properly used (return early!), which should lead to a speed up
* multiple block areas are properly used
* fixes #1905

Fix problems with block_area

---

core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
core/src/test/java/com/graphhopper/routing/weighting/DirectedRoutingTest.java
core/src/test/java/com/graphhopper/routing/weighting/RandomizedRoutingTest.java

Creating the LM routing algo factory should require neither `LMPreparationHandler` nor `PrepareLandmarks`. This PR tries to decouple the corresponding code.

Allow using LM routing algo factory standalone

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java

Fixes #1828 
NameSimilarityEdgeFilter has a circle of radius 100m around the original point. It then looks up the bounding box of the edges and see if they intersect with the circle. This is to help the issue where for some reason or another, it fails to match with the correct road and ends up matching one far away.
I've added a test to make sure it only matches nearby points. For the majority of the matching tests we're only testing name similarity so I used a mock node access that gives 0 distance between the nodes and overloaded the methods.

Add 100m radius restriction to point hint matches

---

core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/TurnCostParser.java
core/src/main/java/com/graphhopper/routing/weighting/DefaultTurnCostProvider.java
core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/BidirPathExtractorTest.java
core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMTurnRelationParserTest.java
core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageWithTurnCostsTest.java
core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
core/src/test/java/com/graphhopper/storage/TurnCostStorageTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java

TurnCostStorage had several layers of read/write methods. To me, it looked like the class couldn't make up its mind if its IntRefs/Encoders should work the same way as for edges, or not. And then got stuck in the middle.
I just removed everything except *one* way of accessing it, namely the one that is used in production code. And adapted all the tests.

Clean up TurnCostStorage

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
core/src/main/java/com/graphhopper/routing/weighting/BlockAreaWeighting.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/Graph.java
core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java
core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java

I think I found a good solution to the graph-dependency problem with always have in the Weighting: now we can fetch the tower nodes only (should be similar fast) without a NodeAccess only via the EdgeIteratorState without introducing a new method.
And additionally I found a minor speed improvement (moved BBox creation out of the loop).
This also helps making stuff in #1776 easier.

Avoid graph dependency

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/AbstractBidirCHAlgo.java
core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
core/src/main/java/com/graphhopper/routing/AbstractRoutingAlgorithm.java
core/src/main/java/com/graphhopper/routing/AlternativeRoute.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractAdjustedWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/QueryGraphWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/Weighting.java
core/src/main/java/com/graphhopper/storage/RoutingCHGraph.java
core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
core/src/test/java/com/graphhopper/routing/AlternativeRouteTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java

Make sure node-based algos are not running with turn costs

---

api/src/main/java/com/graphhopper/config/LMProfileConfig.java
config-example.yml
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/test/java/com/graphhopper/GraphHopperProfileConfigTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
tools/src/main/java/com/graphhopper/tools/Measurement.java
web-api/src/main/java/com/graphhopper/jackson/LMProfileConfigMixIn.java
web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTurnCostsTest.java

Fixes #1980. @karussell can you check if this way this is also useful for #1776?
This is how it works
```yaml
profiles:
- name: my_car
vehicle: car
weighting: some_weighting
- name: my_adjusted_car
vehicle: car
weighting: other_weighting
lm_profiles:
- name: my_car 
- name: my_adjusted_car
preparation_profile: my_car
```

Add config option `preparation_profile` to allow cross-querying in hybrid mode

---

client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
client-hc/src/test/java/com/graphhopper/api/GraphHopperWebTest.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceClientHCTest.java

fixes #2013 
Had to move the timeout test into the same package to avoid making the getClientForRequest method public. Now RouteResourceClientHCTest.java has only integration tests going towards localhost.

timeout should propagate to OkHttp

---

isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ShortestPathTree.java
web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java

This PR adds the ability to limit isochrones by weight as well.
Since weight can be any number, I also made the "offset" configurable as well. Probably offset is not the correct word. Maybe search limit? 
Related to #1979 and #1607

Isochrones just by weight (rather than time or distance)

---

core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java

Details, see https://discuss.graphhopper.com/t/make-instruction-generation-extendable/5493/10?u=boldtrn
I tested this feature with car, bike and the results look alright to me.

Use transportation mode for getOffBike

---

core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

In production this improves visited nodes by at least 10% for a few examples. In our benchmarks this is ~3% faster, but could be also be noise. At least it should improve the warning logs for smaller graphs.

better estimate factor to store landmark weights more precise

---

core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
core/src/main/java/com/graphhopper/routing/subnetwork/TarjansSCCAlgorithm.java

When we are calculating strongly connected components there are very many components with only a single node, especially when multiple vehicles are used. For this reason it has an option to 'ignore' single-node components and before this fix: e6783acb1760c5ffff07c569244fefc97946f5e1 this significantly reduced the time it took to calculate the connected components. However, after this fix this is no longer faster and in fact its a bit slower, because to 'detect' the single-node components also all nodes were traversed. Moreover, the implementation had a bug: Even when using the `ignoreSingleEntries` option the `findComponents` method returned (some) components with a single-entry (which were **also**) added to the `ignoreSet`. So the `ignoreSet` (which is supposed to contain the single …

Clean up TarjanSCC's single-node component handling

---

.gitignore
.travis.yml
config-example.yml
core/files/changelog.txt
docs/core/quickstart-from-source.md
graphhopper.sh
pom.xml
web/package.json
web/pom.xml

This fixes #1700.
Setting up npm is not required for users that only need the API (no web UI), Android or Desktop. But we should still include it in the maven cycle. So I decided to give it a try via a maven profile and the plugin seems to work properly.
The npm_modules are duplicated in web/node/npm_modules in parallel to the "normal" web/npm_modules. Is this bad? (IMO this is fine as we have the maven node&npm stuff and the other is the real locally installed node&npm. But it could also be confusing?)
TODO:
You might want to have a look into this change @easbar @michaz @Nakaner

include npm as part of the maven cycle

---

core/src/main/java/com/graphhopper/routing/AStarBidirectionEdgeCHNoSOD.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
core/src/main/java/com/graphhopper/routing/ch/CHRoutingAlgorithmFactory.java
core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java

For some reason I did not realize earlier that edge-based CH is using Dijkstra by default, even though AStar is significantly faster. The default algorithm is now chosen by the different algo factories and the default algorithm for edge-based CH is now AStar. For the Bavaria map this improves the average routing time from `4.9ms` to `3.3ms`  (-33%). For comparison: With node-based CH we get around `1.4ms`. Edge-based CH is x2.4 slower now.

Use AStar by default for edge-based CH

---

core/src/main/java/com/graphhopper/routing/querygraph/EdgeChangeBuilder.java
core/src/main/java/com/graphhopper/routing/querygraph/QueryGraph.java
core/src/main/java/com/graphhopper/routing/querygraph/QueryOverlayBuilder.java
core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/weighting/QueryGraphWeighting.java
core/src/test/java/com/graphhopper/routing/HeadingResolverTest.java
core/src/test/java/com/graphhopper/routing/querygraph/QueryGraphTest.java
web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java

When we insert a virtual node between two nodes, like nodes 0 and 1 here: 
```
0-x-1
```
four `VirtualEdgeIteratorState`s get created. Two are visible for the edge explorer at the virtual node and one is visible from each of the real nodes (0 and 1). However, these edge states only represent the two directions of the two edges 0-x and x-1 and in fact `edgeState.getEdge()` returns the same number for each pair. Also the virtual edge IDs were not consecutive before this PR. So if 0-1 was the only edge with ID 0 we would get two virtual edge states with ID 1 and two with ID 3. IDs 2 and 4 could still be used to *obtain* the virtual edge states using `graph.getEdgeIteratorState(2,x)` but the returned edge state would still not have edge ID 2 (in this case it would be `edgeState.getEdge()==1` …

Make virtual edge IDs consecutive

---

core/src/main/java/com/graphhopper/routing/AlternativeRouteEdgeCH.java

I was checking the usages of `RoutingCHGraph#getEdgeIteratorState` and saw this todo in `AlternativeRouteEdgeCH`. I think there is no need to unpack the edge because the edge ID we need is already stored in the shortest path entry (CHEntry in this case). Btw at some point we had a `getIncEdge()` method in `SPTEntry` but then decided it is better/ok to just do the cast wherever the incoming edge is needed.

No longer unpack shortcuts to determine head/tail edges

---

.travis.yml

Something is wrong with jdk.java.net, e.g. we got `curl: (56) SSL read: error:0` but other errors too.
So we could switch when moving to adoptopenjdk urls.

Change OpenJDK download server

---

client-hc/pom.xml
core/files/changelog.txt
core/pom.xml
reader-osm/pom.xml

Now that it has been decided that GraphHopper only fully supports Android up to GraphHopper version 1.0 we can update all modules to Java 8. Related: #1940 (I.e. GraphHopper 2.0 drops support for very old Android versions for offline routing)

Update core,client-hc and reader-osm to Java 8

---

tools/src/main/java/com/graphhopper/tools/Measurement.java

@easbar do you know why we include the `average_speed` path details for instructions in Measurement?

withInstructions should be without path details

---

core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java

No real performance improvement even though this method is called frequently in query graph's `isVirtualEdge` method, but anyway no need to create an all edge iterator to find out the number of edges.

Avoid object creation when calling graph#getEdges()

---

navigation/src/main/java/com/graphhopper/navigation/DistanceUtils.java

This PR addresses a minor issue. If I would like to use the method `NavigateResponseConverter#convertFromGHResponse(GHResponse ghResponse, TranslationMap translationMap, Locale locale, DistanceConfig distanceConfig)`, I need to pass a DistanceConfig. The constructor of the DistanceConfig is: `DistanceConfig(DistanceUtils.Unit unit, TranslationMap translationMap, Locale locale)`. `DistanceUtils.Unit` has only package access, so I cannot use it in a different package, therefore I cannot use the `NavigateResponseConverter` from a different package.

Set Unit public

---

web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java

I think this fixes #2083.
TODO

fix bucket size

---

reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

I was browsing through the OSMReader and saw that the three methods:
- processRelation
- processWay
- processNode
Have three different visibility. In one project I am already using the processRelation method to add a hook. Now I wanted to use the processNode method as well and saw that this is not easily possible. I think there are good use-cases to extend all three methods.
WDYT? Would it make sense to set all 3 methods public? Personally I could very well live with setting them protected, but that way at least there is a way to modify it.

Set OSMReader#process methods public

---

core/src/main/java/com/graphhopper/GraphHopper.java

I missed adding a s to the log output for the ferry interpolation

Add seconds to the ferry interpolation log

---

.gitignore

This PR adds the logs folder to the gitignore. This always bothered me, that the logs show up in unversioned files :).
BTW: this is no Hacktoberfest Spam 🍺😇

Add logs to .gitignore

---

README.md

The tag 2.0 and the branch 2.0 made problems and branch was not really named what it was, so renamed it to 2.x (i.e. future releases/tags that are fixes of 2.0 will land there)
Where else do we need to take care of this? In the docs we already use the tag `stable` to avoid changing the docs for every release.

Rename branch 2.0 to 2.x

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/util/CustomModel.java
core/src/main/java/com/graphhopper/routing/weighting/custom/PriorityCalculator.java
core/src/main/java/com/graphhopper/routing/weighting/custom/SpeedCalculator.java
core/src/test/java/com/graphhopper/routing/util/CustomModelTest.java
core/src/test/java/com/graphhopper/routing/weighting/CustomWeightingTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/PriorityCalculatorTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/SpeedCalculatorTest.java
example/src/main/java/com/graphhopper/example/RoutingExample.java

There is a bug which could occur for Java or the API when using multiple encoded values and/or multiple cases for one encoded value. The next goal should be to make CustomModel.getPriority/getSpeedFactor/getMaxSpeed type safe which we might reach when we limit the language to only "clause" as key and number as value (which is a next but much bigger step).

CustomWeighting: ensure Map is ordered

---

core/src/main/java/com/graphhopper/GraphHopper.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
web-bundle/src/main/java/com/graphhopper/http/health/GraphHopperHealthCheck.java
web-bundle/src/main/java/com/graphhopper/resources/HealthcheckResource.java

This PR adds a public facing health check.
Dropwizard provides a healtcheck resource on the admin port, e.g.: http://localhost:8990/healthcheck
Usually, I don't want to expose the admin port to the internet. So I added a minimal endpoint that runs the registered health checks and either returns OK/200 or UNHEALTHY/500.
I also added a health check for the fullyLoaded attribute. I am not sure if you like that? I think we need a few more health checks in the future that also check if the graph is healthy, but I don't have a good idea on how to do this right now.

Add a public facing Healthcheck

---

web/pom.xml

Related to #1388 
According to https://github.com/dropwizard/dropwizard/issues/2318 the issue was fixed with DW 2.0, so we should not need this dependency anymore?
I couldn't see errors when starting the webserver locally.

Remove Activation dependency

---

NOTICE.md
core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/ev/EncodedValueLookup.java
core/src/main/java/com/graphhopper/routing/ev/UnsignedIntEncodedValue.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/weighting/custom/BooleanToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/PriorityCalculator.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
core/src/test/java/com/graphhopper/routing/weighting/CustomWeightingTest.java
web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java

A stricter naming schema for EncodedValue so we can later safely use an EncodedValue as a variable in expressions.
Incl. minor bug fix in BooleanToValueEntry.

Stricter naming of EncodedValue 

---

core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java

With #2198 we have stricter naming but we still allow `.` although this is not allowed in a Java variable.
This is a bit ugly as we can currently use the non-shared EncodedValues like `car.access` or `car.average_speed` or `bike.access` in the CustomWeighting. They are "non-shared" because the FlagEncoder creates and populates them - this will be moved into a separate TagParser in the future, but for now we have to detect it as a special case because these EncodedValues should be excluded when storing+loading all encoded values. This will disappear when FlagEncoders dissolve. 
This change is basically a change to make master forward compatible with the janino_scripting branch, i.e. also allow non-shared EncodedValues in the new CustomWeighting with janino scripting. As variables with `.` …

Change of non-shared EncodedValue

---

core/src/main/java/com/graphhopper/routing/util/EncodingManager.java

Added the following entries: 
- `_` (underscore is a keyword since Java 9)
- false, true
- null
- sealed, non-sealed, permits (JEP 360)
- record (JEP 395)
- var, yield (restricted identifiers)
https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9

Extend the list of restricted encoded value names

---

core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/DirectedBidirectionalDijkstraTest.java
core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
core/src/test/java/com/graphhopper/routing/subnetwork/TarjanSCCTest.java

In #2202 we 'broke' `GHUtility#buildRandomGraph` because 
1) if `speed!=null` the calls to `random.nextDouble` for `fwd/bwdSpeed` were skipped (so we e.g. got different distances for the same seed), even though previously these calls were executed even for `randomSpeedEnc!=null`.
2) we accidentally disabled the random speed generation by passing `speed=60d` in places where we previously passed `randomSpeedEnc=null` (which meant that random speeds should be enabled). Where we previously passed `randomSpeedEnc!=null` we now need to pass `speed=null` and where we previously passed `randomSpeedEnc=null` we now need to pass `speed=60` (at least for car).
Also c.f. this comment: https://github.com/graphhopper/graphhopper/pull/2202#discussion_r541996509

Use random speeds for random graphs to restore behavior before #2202

---

core/src/main/java/com/graphhopper/routing/DefaultWeightingFactory.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelper.java
core/src/main/java/com/graphhopper/routing/weighting/custom/ExpressionBuilder.java
core/src/main/java/com/graphhopper/routing/weighting/custom/SpeedAndAccessProvider.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/ExpressionBuilderTest.java

Here I tried separating the custom model parsing from the custom weighting creation a bit, such that e.g. we can test extracting speeds and priorities from the custom model definition without creating a `CustomWeighting`.
Follow-up of this comment: https://github.com/graphhopper/graphhopper/pull/2209/files#r541899846

Custom weighting helper cleanup

---

web-bundle/src/main/java/com/graphhopper/http/MultiExceptionMapper.java

Our `MultiException` constructor calls the default `RuntimeException` constructor , so the `detailsMessage` field in `Throwable` is always `null`. Therefore we log `unknown reason` for many errors. I changed this so we see more details on e.g. 400 errors like this:
```
com.graphhopper.http.MultiExceptionMapper: bad request: unknown reason
com.graphhopper.http.MultiExceptionMapper: bad request: [java.lang.IllegalArgumentException: The 'heading' parameter is currently not supported for speed mode, you need to disable speed mode with `ch.disable=true`. See issue #483]
```
Not sure, we could also properly set the message in `MultiException` and skip `java.lang.IllegalArgumentException` for the output, but this seemed like the minimal fix..

Log MultiException properly

---

core/src/main/java/com/graphhopper/reader/dem/EdgeSampling.java
core/src/test/java/com/graphhopper/reader/dem/EdgeSamplingTest.java
example/src/main/java/com/graphhopper/example/RoutingExampleTC.java
reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
reader-osm/src/test/java/com/graphhopper/GraphHopperTest.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java

During import we calculate `edge.getDistance()` before we simplify the edge geometry. Therefore the edge distance can be different to the distance we would calculate from the edge geometry:
```java
edge.getDistance() != new DistanceCalcEarth().calcDistance(edge.fetchWayGeometry(FetchMode.ALL));
```
This doesn't seem right, so in this PR I moved the edge simplification in front of the distance calculation.

Simplify edge geometry before the distance is calculated

---

.gitignore
config-example.yml
docs/core/quickstart-from-source.md
pom.xml
web/package.json
web/pom.xml
web/src/main/java/com/graphhopper/http/CORSFilter.java
web/src/main/java/com/graphhopper/http/GraphHopperApplication.java
web/src/main/java/com/graphhopper/http/GraphHopperServerConfiguration.java
web/src/main/resources/assets/js/config/options.js
web/src/main/resources/assets/js/graphhopper/GHRequest.js

The configurable-assets-bundle was used so we can edit the maps JavaScript code while the server is running(?). However, we were already pointing the bundle override into web/target/classes in config-example.yml and if we change the files there our changes will be reflected in the browser already without the configurable-assets-bundle. Therefore I do not see why we need this?
With this PR we (still) can edit main-template.js or any of the other javascript files of the map client and see the changes after a page reload byrunning `npm run watch` which will browserify all the files and copy the resulting `main.js` file to web/target/classes/assets whenever we make a change. Changes to `index.html` are not reflected and we would need some mechanism that updates `index.html` in the target …

Remove configurable-assets-bundle

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java

Solving issue #2240 
CustomModelParser used to create a Java file with a JsonFeature called feature. In case of multiple areas the JsonFeature was created twice.
The following is the code created by CustomModelParser.
@Override
public void init(EncodedValueLookup lookup, com.graphhopper.routing.ev.DecimalEncodedValue avgSpeedEnc, Map<String, com.graphhopper.util.JsonFeature> areas) {
this.avg_speed_enc = avgSpeedEnc;
JsonFeature feature = (JsonFeature) areas.get("milano");
this.in_area_milano = new Polygon(new PreparedGeometryFactory().create(feature.getGeometry()));
JsonFeature feature = (JsonFeature) areas.get("modena");
this.in_area_modena = new Polygon(new PreparedGeometryFactory().create(feature.getGeometry()));
if (lookup.hasEncodedValue("road_class")) this.road_class_enc = …

CustomModelParser can handle multiple areas

---

core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

A [Kurviger](https://kurviger.de/) user just reported an interesting bug. A [road](https://www.openstreetmap.org/way/115560610) was classified as oneway from the routing engine even though it is not marked as a oneway.
The issue is created in the isOneway method, where we only check if a `*:forward ` or `*:backward` tag exists but not if this tag actually marks it as a oneway.
Therefore I propose to check if these tags are actually indicating that a restrictive value is set.
This situation doesn't seem to happen frequently, but there are a few ways like this.

Incorrectly classified oneways

---

web-bundle/package.json
web-bundle/src/main/resources/com/graphhopper/maps/js/map.js

I updated the heightgraph version. One thing I noticed is that in master the 'elevation highlighting' is not updated while moving the slider (on the right y-axis of the diagram) and after moving it it annoyingly jumps back to zero when I try to move it again. But this seems fixed with the new version. (Update: Yes this was: https://github.com/GIScience/Leaflet.Heightgraph/issues/42). Also with 1.4.0 it is possible to use a continuous color scale for numeric path details like average_speed or time. Will do this in a follow-up PR.
@boldtrn Thanks for developing the elevation diagram. Do you think there is an issue with this update? I already adjusted the x-ticks (they were too frequent, probably since 0.4.1) and checked the css file (its the same except a folder name img/images).

Update leaflet.heightgraph 0.2.0 -> 1.4.0

---

web-bundle/package.json
web-bundle/src/main/resources/com/graphhopper/maps/index.html
web-bundle/src/main/resources/com/graphhopper/maps/js/graphhopper/GHRequest.js
web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js
web-bundle/src/main/resources/com/graphhopper/maps/js/map.js

I added a new `selected_detail` url parameter to the maps UI. It stores the selected detail in the elevation diagram so we can keep the selection in between requests (e.g. when we shift the markers or update the custom model).
This PR depends on #2257

Keep elevation diagram selection between requests

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CONTRIBUTING.md
CONTRIBUTORS.md

I propose to remove the requirement of a CLA.
We never used the CLA to take away ownership or had the right to relicense the code, but still this requirement added a lot of friction. And so other companies like Chef or Amazon do not require CLA.
IMO we can safely assume that everyone who contributes understands that this project is Apache licensed and so the contribution will be under the same license.

No more contributor license agreement

---

core/src/main/java/com/graphhopper/routing/AlgorithmOptions.java
core/src/main/java/com/graphhopper/routing/FlexiblePathCalculator.java
core/src/main/java/com/graphhopper/routing/RoundTripRouting.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactory.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java
core/src/main/java/com/graphhopper/routing/util/TestAlgoCollector.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java
core/src/test/java/com/graphhopper/routing/lm/LMIssueTest.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java

AlgorithmOptions#weighting does not work very well, because the weighting can not be chosen arbitrarily for all algorithms (namely CH). The Builder seems rather unnecessary and makes AlgorithmOptions a lot more complicated than it probably needs to be. It is not even really immutable as it claims to be because of the PMap.
Actually I am still not satisfied and rather want to remove AlgorithmOptions and the RoutingAlgorithmFactory interface entirely, but I did not manage to do this yet. This PR is a step into this direction though.

AlgorithmOptions: Remove weighting and builder

---

client-hc/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java
client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
client-hc/src/test/java/com/graphhopper/api/AbstractGHMatrixWebTester.java
client-hc/src/test/java/com/graphhopper/api/GHMatrixBatchTest.java
client-hc/src/test/java/com/graphhopper/api/GHMatrixSyncTest.java
client-hc/src/test/java/com/graphhopper/api/GraphHopperWebTest.java

Client HC included an empty string for the `"vehicle"` parameter for matrix requests even when no vehicle was given. `GraphHopperWeb` already handled this correctly but there is no need to add `vehicle` to the `ignoreSet`.

Do not include empty vehicle in client hc for POST matrix requests

---

pom.xml

version upgrade of commons-io (to 2.7) and dropwizard (to 2.0.21)

upgrade some dependencies

---

core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/test/java/com/graphhopper/routing/weighting/BlockAreaWeightingTest.java

BlockArea currently treats an empty GHIntHashSet the same way as a non-existing cache for blocked edges. But a small shape which doesn't cover edges in the graph would also yield an empty GHIntHashSet. For those cases BlockArea would resort to the more expensive bbox/shape intersection logic:
https://github.com/graphhopper/graphhopper/blob/0522c495ccad5f22fe19c6e858a40a7bd6f74eae/core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java#L198-L223
I changed the logic to explicitly store `null` as the cache for blocked edges if the shape is to large so we can properly determine if we have no cache or if it's just empty.

Skip shapes which don't block any edges

---

map-matching/src/main/java/com/graphhopper/matching/MapMatching.java

MapMatching uses the weighting and access the turn costs data of the baseGraph even for virtual nodes that can lead to rare exceptions ala:
```
java.lang.ArrayIndexOutOfBoundsException: Index 4476 out of bounds for length 4476
at com.graphhopper.storage.RAMIntDataAccess.getInt(RAMIntDataAccess.java:208)
at com.graphhopper.storage.GHNodeAccess.getTurnCostIndex(GHNodeAccess.java:90)
at com.graphhopper.storage.TurnCostStorage.readFlags(TurnCostStorage.java:186)
at com.graphhopper.storage.TurnCostStorage.readFlags(TurnCostStorage.java:181)
at com.graphhopper.storage.TurnCostStorage.get(TurnCostStorage.java:167)
at com.graphhopper.routing.weighting.DefaultTurnCostProvider.calcTurnWeight(DefaultTurnCostProvider.java:69)
at com.graphhopper.routing.weighting.AbstractWeighting.calcTurnWeight(Abstra …
```

map matching: properly access turn costs for virtual nodes

---

api/src/main/java/com/graphhopper/GraphHopperAPI.java
client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java

This method is not really used in a meaningful way. The main users of `GraphHopperAPI`:  `RouteResource` and `NavigateResource` do not use it either.

Remove GraphHopperAPI#load

---

web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js

Loading an external JSON is ugly as we hit an external URL (potential security problem, slower and no way to quickly edit)
This PR uses the custom_model JSON directly from the URL.
For a short URL and to properly URL encode the `&&` I suggest e.g. https://www.minifyjson.org/ (tick at 'Convert all &') before copying into the URL.

use custom_model parameter directly in GH Maps URL

---

core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelper.java
core/src/main/java/com/graphhopper/storage/GraphEdgeIdFinder.java
core/src/main/java/com/graphhopper/util/shapes/Polygon.java

If a polygon describes a rectangle, we don't need to load the way geometry to check for an intersection.
This should be especially beneficial for large areas, for which we previously had to load all intersecting edge geometries.

Use bbox intersection logic for rectangles

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/WheelchairFlagEncoderTest.java
core/src/test/resources/com/graphhopper/reader/osm/test-barriers.xml
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java

Replaces #2344
- make absolute barriers passable (now called `blockByDefaultBarriers`)
- car now also allows passing "potential barriers" by default (those barriers are now called `passByDefaultBarriers`)
- removal of configuration option "blockByDefault".

make absolute barriers passable

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/WheelchairFlagEncoder.java
core/src/main/java/com/graphhopper/storage/StorableProperties.java
core/src/main/java/com/graphhopper/util/Constants.java
core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java

We do not need to keep track of the versions in that much detail, base graph's version (nodes, edges, geometry etc.) should be enough. Also we want to get rid of `FlagEncoder` anyway.

Remove FlagEncoder#getVersion

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/osm/GraphHopperOSM.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupHelper.java
docs/core/spatial-rules.md
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
web/src/main/java/com/graphhopper/http/cli/ImportCommand.java

After #2354 we can now move some of the code in `GraphHopperManaged` closer to where it is actually used. Particularly we were parsing the landmark splitting borders geojson and spatial rule borders geojson files in `GraphHopperManaged` and 'injected' this code into `GraphHopper`. But the only reason we did this was that we weren't able to read geojson in core.
Also for #2353 I'd like to read the countries.geojson and other custom area geojson files directly from the GraphHopper class.
Related to #2365

Move landmark splitting and spatial rule border parsing from web-app into core

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java

Fixes #1454.
Prefering ways with "bicycle=use_sidepath" is the opposite to what is correct for bicycles. Now we are avoiding these ways.
See https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath.

Avoid "bicycle=use_sidepath" ways instead of preferring it.

---

pom.xml

This PR updates the used version of Apache Commons Compress. There are security vulnerabilities with 1.19: 
- https://nvd.nist.gov/vuln/detail/CVE-2021-35515
- https://nvd.nist.gov/vuln/detail/CVE-2021-35516
- https://nvd.nist.gov/vuln/detail/CVE-2021-35517
- https://nvd.nist.gov/vuln/detail/CVE-2021-36090
Probably not critical as we only use this for OSM files with bzip2 compression.

Update Apache Commons Compress

---

CHANGELOG.md
CONTRIBUTORS.md
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/ElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/GMTEDProvider.java
core/src/main/java/com/graphhopper/reader/dem/MultiSourceElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/SRTMGL1Provider.java
core/src/main/java/com/graphhopper/reader/dem/TileBasedElevationProvider.java
core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/reader/dem/EdgeSamplingTest.java

Refactor elevation provider:
- clean up interface;
- add a getEle(node) variant with a default implementation.
Fixes: #2374.
Ping @otbutz, @easbar.
I did not introduce constructor parameters as it was a bit tricky with multiple constructors like in MultiplSourceElevationProvider.
The `AbstractElevationProvider` was alreading containing filesystem related code so I moved the methods there.
I have not renamed `getInterpolate` to `canInterpolate` yet. I will work on it later.
Please let me know your feedback of this PR.

Refactor elevation provider

---

core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/util/Constants.java

Looks like we do not need the EncodingManager in BaseGraph, see comments inline

Remove EncodingManager from BaseGraph, cleanup nodes and edges header

---

core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/GHNodeAccess.java
core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
core/src/main/java/com/graphhopper/storage/RoutingCHGraphImpl.java
core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java
web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
web-bundle/src/main/java/com/graphhopper/resources/SPTResource.java

So far we were able to access the node storage even outside of its bounds:
```java
GraphHopperStorage g = new GraphBuilder(encodingManager).create();
// no nodes, no edges...
graph.createEdgeExplorer().setBaseNode(5).next(); // -> no error! (also no edges)
```
This is because the created storage is initialized here: 
https://github.com/graphhopper/graphhopper/blob/a48b43ed9fbae6c06e54dc3b5afaf55971b5e475/core/src/main/java/com/graphhopper/storage/BaseGraph.java#L367
However, quite arbitrarily, this fails:
```java
GraphHopperStorage g = new GraphBuilder(encodingManager).create();
// again no nodes, no edges...
g.createEdgeExplorer().setBaseNode(87381).next(); // -> error!
```
because the node index `87381` is just out of range. This depends on the bytes parameter given to `create()` (here …

Add range check for node access

---

core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/main/java/com/graphhopper/routing/subnetwork/SubnetworkStorage.java
core/src/main/java/com/graphhopper/search/StringIndex.java
core/src/main/java/com/graphhopper/storage/DataAccess.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/storage/Storable.java
core/src/main/java/com/graphhopper/storage/StorableProperties.java
core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java

We do not really use any objects through this interface. All it does is enforce a certain lifecycle for some of our persistence related classes. I think this lifecycle is a bit flawed. For example I don't think it is a good idea to create objects and `load` or `create` them afterwards. I would rather either create an object by loading it or just create it and save it later. As a first step I have removed the Storable interface here as it does more harm than good IMO.

Remove Storable interface

---

config-example.yml
core/src/main/java/com/graphhopper/GraphHopper.java

I think that the documentation does not match the code. At the moment the default is "disabled country rules".

country_rules: fix documentation in example config

---

hmm-lib/pom.xml

We switched to Junit5 some time ago. Junit5 requires Java 8. The hmm-lib is still on Java 7. 
When you try to execute the `ViterbiAlgorithmTest` in InteliJ, there is a build error, as the pom sets the language level to Java 7.
```
/graphopper/graphhopper/hmm-lib/src/test/java/com/bmw/hmm/ViterbiAlgorithmTest.java:153:9
java: cannot access java.util.function.BooleanSupplier
class file for java.util.function.BooleanSupplier not found
```
Bumping the version to Java 8 fixes that problem. Running through the command line works fine, so I am a bit unsure about this change, but I guess bumping the version should not hurt?

HMM-Lib: Bump Java version to 8

---

core/src/main/java/com/graphhopper/routing/util/countryrules/AustriaCountryRule.java
core/src/main/java/com/graphhopper/routing/util/countryrules/CountryRuleFactory.java
core/src/main/java/com/graphhopper/routing/util/countryrules/GermanyCountryRule.java

* avoids the need for static `RULE` instances
* allows lib users to easily manipulate registered rules without having to implement their own factory
See discussion in https://github.com/graphhopper/graphhopper/issues/2404

Register country rules in a map

---

core/src/main/java/com/graphhopper/reader/dem/AbstractSRTMElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
core/src/test/java/com/graphhopper/reader/dem/CGIARProviderTest.java
core/src/test/java/com/graphhopper/reader/dem/GMTEDProviderTest.java

We reduce the segment size (1MB) by default for elevation tiles where the elevation is equal to the sealevel everywhere anyway. However, this only affects a minor fraction of these tiles so no real need for this optimization.
Getting rid of this will help with #1794, but once we got rid of the `loadExisting` lifecycle of `DataAccess` we can probably easily put it back if we really want to. Another option could be to just always use the smaller segment size (also for the normal elevation tiles), but not sure how this will affect performance.

Remove small segment size optimization for sea level elevation tiles

---

core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadAccessParser.java

The OSMRoadAccessParser currently ignores the parsed access and always passes RoadAccess.YES to the CountryRule

Don't ignore parsed access

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParser.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMMtbRatingParserTest.java

Sometimes mappers seem to use `mtb:scale=12` or `mtb:scale=34`. They probably mean "S1/2", or "S3/4", but this is not recommended in the OSM wiki: https://wiki.openstreetmap.org/wiki/Key:mtb:scale?uselang=en. The wiki encourages mappers to use `1+` or `2-` instead of `S1/2` for example. There are less than 20 occurrences of `12`, `23` and `34` for the whole planet according to taginfo, so I think we can just ignore this. We already ignore the finer separation using `+/-` which is recommended in the wiki (and somewhat popular) btw.
This PR ignores values above 6. In current master we get an exception during import because the EV's maximum value is exceeded.

Ignore too large mtb:scale values

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/ev/RoadEnvironment.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParserTest.java

See #2465. The alternative to removing it would be making sure it is actually used and handled properly also for snap_prevention and elevation interpolation.

Remove RoadEnvironment.SHUTTLE_TRAIN

---

CHANGELOG.md
core/src/test/java/com/graphhopper/GraphHopperTest.java

* extended the existing unittest to check the type of the exception and if the details are properly populated
* mentioned the new exception in the changelog
see https://github.com/graphhopper/graphhopper/pull/2464#issuecomment-982378307

Cover MaximumNodesExceededException with unittest

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/search/StringIndex.java

Test have passed under following command
```sh
mvn clean test verify
```
Two tests
```
com.graphhopper.search.StringIndexTest.putDuplicate
com.graphhopper.search.StringIndexTest.testLoadKeys
```
failed under [NonDex](https://github.com/TestingResearchIllinois/NonDex) which detect flakiness under non-deterministic data structure usages.
The potential problem I am seeing is that `StringIndex.getAll(...)` [internally uses HashMap](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/search/StringIndex.java#L200). As you may have known that `HashMap` does not guarantee the order consistency under different environment.
**Quoted from [Oracle Java 8 Doc](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html)**
> This class makes no guarantees as …

Fix HashMap related flaky tests

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/test/java/com/graphhopper/GraphHopperTest.java

Fixes #2498. 
I probably introduced this bug when I was working on #2481. When we call `GraphHopper#load` and preparations are only loaded so there is nothing else to prepare we need no write access. I therefore put back the `ensureWriteAccess` calls that we just removed to partially fix the bug in 674828b1d5d987401d62fadc6cfdcca5ba0d50cd, but under the condition that there are actually things to prepare.
Closing the location index, names and way geometry storage is done unconditionally, because they aren't needed in any case (neither if there are CHs to prepare, nor if there are no CHs to prepare). We can even close the way geometry and names before the LM preparation (unless there are no custom profiles), which saves some memory if the import only includes LM.
@michaz, @oli0044 does …

Do not ensure write access when there are no CHs/LMs to prepare

---

core/src/test/java/com/graphhopper/GraphHopperTest.java

For a `car` profile with turn costs, e.g. this route http://localhost:8989/maps/?point=50.018339%2C11.502782&point=50.017515%2C11.501698&point=50.017129%2C11.504467&locale=en-US&elevation=false&profile=car&use_miles=false&layer=Omniscale&details=average_speed fails with an error like
```
node: 1942 out of bounds [0,1942[
```
(depending on the size of the map). The reason is that the turn cost storage is queried with a virtual node ID (node 1942 is a virtual node and thus beyond the range of valid node IDs). The error only occurs when the `average_speed` path detail is enabled and a virtual node is part of the route between two via points. So in the simplest case a route with one via-point A-B-C is such that we visit A again when we go from B to C. Otherwise the error does not occur, …

Node out of bounds error when using average_speed path detail

---

core/src/main/java/com/graphhopper/routing/ch/CHParameters.java
core/src/main/java/com/graphhopper/routing/ch/NodeBasedNodeContractor.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/main/java/com/graphhopper/util/MiniPerfTest.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
tools/src/main/java/com/graphhopper/tools/CHImportTest.java

Fixes #2507.
> Two things we could do to improve this:
After lots of experimenting I arrived at a version that works well for car and foot (and country_rules as well) using default parameters (the same for both profiles). I still use neighbor updates as in #2491, because this allows reducing the shortcut numbers, but I went back to adjusting the maximum number of settled nodes based on the mean degree of the graph instead of keeping it constant throughout the entire preparation. The factor that is used to determine the number of maximum number of settled nodes from the mean degree is now a tuning parameter (actually two: one for priority calculation and one for the contraction). There is also another new parameter that allows limiting the number of neighbor updates *per node*.
To …

Speed up CH for foot

---

reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphExplorer.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphHopperGtfs.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/GtfsReader.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/GtfsStorage.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/Label.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterFreeWalkImpl.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterImpl.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/TripFromLabel.java
reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java

Insert WalkLegs into the response itinerary for all transfers that are not specified in the GTFS, but that were "interpolated" by walking the road network.

Transfer legs

---

core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java

Currently we do:
```
encoder.handleWayTags()
encodingManager.handleNodeTags() // sets access to false if encoder.isBarrier() == true)
encoder.applyWayTags()
```
In #2469 `applyWayTags` should go into `handleWayTags` so right now this would mean it would run before `handleNodeTags`. But first I think we should move `handleNodeTags` to the encoder (this PR), because the encoders should handle the access flags directly (not indirectly via isBarrier as we do now). I therefore moved the code that blocks barriers into a new `handleNodeTags` method in `AbstractFlagEncoder` and this method is called in `encodingManager.handleWayTags` now.
Later I'd like to go further and push this code down into the single flag encoders such that everything related to the access flags will be in one place per …

Move handleNodeTags from EncodingManager to AbstractFlagEncoder

---

CHANGELOG.md
core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/reader/osm/WaySegmentParser.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/Bike2WeightFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FerrySpeedCalculatorTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/MotorcycleFlagEncoderTest.java

Work for #2526.
The `estimated_distance` tag is now called `beeline_distance` and represents the straight line distance between the tower nodes of the edge, not the straight line distance between the first and last nodes of the OSM way as `estimated_distance` did (at some point). We can also use this for the bendiness calculation without `applyWayTags` (see #2469). The actual length of the road/edge is now stored in an artificial tag `road_distance` and we get the full point list of the edge by `point_list`.
More comments inline.

Clean up FerrySpeedCalculator, use exact edge distance

---

core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FerrySpeedCalculatorTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

In case there is a duration tag we need to use the distance of the entire way to calculate the speed (see #2528), but when it is missing we should actually use the distance of the edge instead, because there are some ferry ways that visit multiple places like this one: https://www.openstreetmap.org/way/996639224. There are also ferry ways that cross each other. In principle this could mean that a 'long' ferry is split into two 'shorter' parts for which we apply a slower speed (or will apply a slower speed when we fix #2532). But in reality this seems to only happen close to the harbour, so a long ferry really only might be split into a (still) long edge and a (very) short edge. In this case it would be fine to determine the speed for each edge separately, based on the distance of the edge …

Improve handling of short ferries without duration tag

---

core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/main/java/com/graphhopper/routing/InstructionsHelper.java
core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
core/src/main/java/com/graphhopper/routing/util/FiniteWeightFilter.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java

Use Weighting instead of access for turn instructions

---

CHANGELOG.md
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/routing/OSMReaderConfig.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/RouterConfig.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
web-api/src/main/java/com/graphhopper/util/Parameters.java

I moved the code that parses the `name/ref` OSM tag of the OSM ways from `EncodingManager#applyWayTags` to `OSMReader`. I also added a new setting to disable instructions on the server side called `routing.instructions`, which is now separated from `datareader.instructions`. The latter now only controls whether the way names shall be parsed or not. It is probably debatable whether we even need `datareader.instructions` and it should probably be better renamed to `datareader.parse_names` or even `osmreader.parse_names`. However renaming `datareader` to `osmreader` is for another issue.

Move way name parsing from EncodingManager to OSMReader

---

map-matching/src/main/java/com/graphhopper/matching/MapMatching.java
map-matching/src/main/java/com/graphhopper/matching/Observation.java
web/src/test/java/com/graphhopper/application/MapMatchingTest.java

Map-matching has a very old think-bug made when the "filtering" of the input points was added: The original linear distance between the input points would not be preserved, so the entire estimator is biased towards shorter routes, which makes it cut corners like this for even the default value of `measurementErrorSigma`:
Not anymore.
(The entire feature was, of course, a Performance Optimization. I hope to remove it next time I comb through map matching, since I have an idea to make it faster.)

Fix bias in map-matching

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/AStar.java
core/src/main/java/com/graphhopper/routing/AStarBidirection.java
core/src/main/java/com/graphhopper/routing/AbstractBidirCHAlgo.java
core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
core/src/main/java/com/graphhopper/routing/Dijkstra.java
core/src/main/java/com/graphhopper/routing/SPTEntry.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
tools/src/main/java/com/graphhopper/tools/Measurement.java

`PriorityQueue#remove` is an expensive operation, especially for large queues as it has O(N) complexity. We use it for Dijkstra and related algorithms, because there is no efficient update operation: We simply remove the old entry and add the updated entry. An alternative approach is to flag the old entry, add a new one and ignore the flagged ones when polling from the queue. @michaz already did this for isochrones some time ago: #2092
We tried this for the other algorithms already in the past, but without success so far: #489, https://github.com/graphhopper/graphhopper/pull/2107, https://github.com/graphhopper/graphhopper/issues/2408
Trying this again I think this change clearly speeds up the flexible (non-CH) algorithms, especially for the edge-based traversal mode. In our measurements …

Stop removing elements from the priority queue, speeds up flexible algorithms

---

core/src/main/java/com/graphhopper/GraphHopper.java

We already log if we are using custom areas. This makes it a bit easier for library users to tell if their own rules are getting properly applied.

Log available country rules

---

core/src/main/java/com/graphhopper/routing/util/DefaultFlagEncoderFactory.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoders.java
core/src/main/java/com/graphhopper/routing/util/VehicleEncodedValues.java
core/src/test/java/com/graphhopper/util/InstructionListTest.java

With this PR the default is `roads|is_motor_vehicle=true|is_hgv=false` (as before), but now we can change it.
Note that currently the turn costs are hard-coded for this encoder, i.e. setting `turn_costs=false` would not have an effect.

Make motor vehicle and hgv properties configurable for roads vehicle EVs

---

core/src/main/java/com/graphhopper/routing/SPTEntry.java
core/src/test/java/com/graphhopper/routing/AStarBidirectionTest.java
map-matching/src/main/java/com/graphhopper/matching/MapMatching.java

In some rare cases we can run into a 'Calculating time should not require to read speed from edge in wrong direction' exception when using LM. The problem occurs, because the LMApproximator is not feasible in combination with virtual edges: #2584, which would normally result in a suboptimal path in the worst case. However, such a sub-optimal path can contain shortest path tree entries that we flag as 'deleted' since #2571. We are abusing the `adjNode` field to mark these entries as 'deleted' using a special value of `Integer.MIN_VALUE`. When the path is extracted and we get the corresponding edge iterator state using `graph.getEdgeIteratorState(edge, adjNode)` this means that the special value of `Integer.MIN_VALUE` yields the edge state in storage direction, which can, of course, be the …

Use separate deleted flag for SPTEntry, prevent exception when calculating routes with non-feasible approximator

---

core/src/main/java/com/graphhopper/routing/ch/CHPreparationGraph.java
core/src/test/java/com/graphhopper/routing/ch/CHPreparationGraphTest.java

Since #2567 we store the edge key instead of the edge ID in CHPreparationGraph#OrigGraph, which is used (only) for edge-based CH preparation. Before this the maximum possible edge ID was around 536mio (`Integer.MAX_VALUE >> 2`), but due to the change now the maximum possible edge **key** is around 536mio, which means that the import will fail if the base graph has more than around 268mio edges! 
However, we did not use the unsigned bitshift operator so far which means we were applying a limit that was below the physical limit implied by the 30bits we reserve for the edge ID/key. Using the unsigned shift the maximum is around 1 billion (`Integer.MAX_VALUE >> 1`) and since we are now storing edge keys this means the maximum number of edges is around `536mio` when we use the unsigned shift. …

Increase maximum edge-based CH key for preparation to 2^30 again

---

web-bundle/package.json

This adds support for the new right-hand side expressions for the `limit_to` and `multiply_by` operators in custom models that we introduced in #2568.
The auto-complete suggestions include all numeric encoded values and simple arithmetic expressions like `50 + car_average_speed * 0.9` are allowed. Only `+`,`-` and `*` and only one encoded value per expression is allowed.
@karussell can you try this?

Update custom model editor: validation + auto-complete for rhs expressions

---

web-bundle/src/main/resources/com/graphhopper/maps/js/map.js

I added two elevation diagram details: 'Slope' shows the slope of every path segment (between pillar nodes) and 'Towerslope' shows the slope between tower nodes only. Both are calculated on the client-side from the point list. 'Slope' is always shown and 'Towerslope' is only shown when the `edge_id` detail is enabled (because this is needed to calculate 'Towerslope' and both can be considered debug features). For 'Towerslope' I also adjusted the elevations (skipped those of the tower nodes so the diagram matches the slope values):
The colors indicate the absolute slope value (e.g. -5 is the same color as +5) and the spectrum ranges from 0 (blue) to 25 (red).

Maps: Add slope detail to elevation diagram

---

core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelper.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingHelperTest.java

Fixes #2683
We should only early-out if the rectangle fully contains the bounding box of the edge. This still avoids costly way geometry checks in most cases but improves accuracy for checks near the borders of the polygons bounding box.

Improve area check precision

---

config-example.yml
core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/ev/OSMWayID.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMWayIDParser.java
core/src/test/java/com/graphhopper/routing/ev/IntEncodedValueImplTest.java

This PR adds a parser and encoded value for OSM way IDs. GraphHopper creates one or more edges for each OSM way and with this PR we can retrieve the ID of the OSM way each edge was created from at runtime. This has been requested many times in the context of map-matching for example or can be used block certain OSM ways (using custom models for example). At the very least it is useful for debugging.
It is important to consider that OSM way IDs can change any time. So whenever one runs a new import with an updated map file their values might change. For this reason the new `osm_way_id` encoded values is not enabled by default, but can be enabled via `graph.encoded_values` in `config.yml`.
OSM uses 64bit integers to store OSM way IDs, but in reality the largest ID is currently around 1.1 …

Add OSM way ID encoded value

---

core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/ev/Footway.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMFootwayParser.java

Here I added a footway encoded value for the footway=sidewalk,crossing,... etc. tag: https://wiki.openstreetmap.org/wiki/Key%3Afootway, fixes #2692 
I briefly tried calculating some pedestrian routes that avoid crossings in Berlin. Note that almost none of these red-dashed separate footways were mapped in OSM at the beginning of this year! See also here: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende. 
The new footway encoded value simply parses the footway=* tag without any further thoughts. Calculating good pedestrian routes is another story though. For example we can easily use a custom model to prevent footway=crossing (see screenshots), but care must be taken that as a result the route does simply use the normal roads (like tertiary) instead. Therefore I also lowered the …

Add footway encoded value

---

CHANGELOG.md
config-example.yml
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java

Another try after #2733, this time each thread writes the subnetwork flags to a separate bit set and the actual subnetwork encoded values are written synchronously afterwards. This requires `E/8` bytes of memory per thread where `E` is the number of edges. So for a planet-wide import with 500mio edges we need around 60MB of extra memory per thread which shouldn't really matter. 
This feature can be enabled by setting `prepare.subnetworks.threads` to something like `2` or larger in `config.yml`. The maximum sensible value is the number of profiles.

Use multi-threading for subnetwork preparation

---

core/src/main/java/com/graphhopper/reader/osm/OSMInputFile.java
core/src/main/java/com/graphhopper/reader/osm/SkipOptions.java
core/src/main/java/com/graphhopper/reader/osm/WaySegmentParser.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfDecoder.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfReader.java

Currently we read the OSM file twice during import and there even were some suggestions to read it three times (e.g. for #2765 or #82). With the simple tweak in this PR we can reduce the time it takes to read the file if we are only interested in certain OSM elements.
I did a quick check using a map of Germany with ~356mio nodes, ~58mio ways and ~0.7mio relations, with two worker threads. Reading the file (just counting the elements, and doing nothing else) took around 113s using master, around 73s using this branch when I skipped the nodes and 56s when I skipped both nodes and ways.
We can already use this for our current import where we can skip the reading of nodes in the first pass, which speeds up the import.

Allow skipping the creation of ReaderNodes/Ways/Relations for pbfs, skip nodes in first pass of OSM import

---

core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/test/java/com/graphhopper/GraphHopperTest.java

Currently there are no u-turn instructions for 'simple' u-turns where we simply turn around on the same road/edge. We only show instructions for such u-turns when the occur at via-points, and we even show instructions for the (more complicated) u-turns that use a via-way:
The image shows a u-turn at the via-point 1, blue marker. We get an instruction for this, but not the u-turn at the end of the dead-end road near the red marker. The reason we get this u-turn is a curbside constraint at the red marker.
Here is an example for a u-turn that includes a via-way, and for which we already show a u-turn instruction:
In this PR I added a u-turn instruction for the simple kind of u-turns, like the one near the red marker in the first screenshot.
I also wonder if we should distinguish between …

Show u-turn instruction for plain u-turns

---

core/src/main/java/com/graphhopper/util/PathMerger.java
core/src/main/java/com/graphhopper/util/details/ConstantDetailsBuilder.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/main/java/com/graphhopper/util/details/PathDetailsFromEdges.java
web-api/src/main/java/com/graphhopper/util/Parameters.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceClientHCTest.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceTest.java

When we query `/route` with via-points it returns the time, distance, weight and coordinates of the entire route. But so far there is no direct information about the time/distance/weight of the single sections between the (via) points. Also it is not very clear how the global point list can be separated for the single sections ('legs'). We can work around this using instructions or path details like 'time', but this is rather cumbersome and enabling instructions or certain path details just for this purpose can decrease performance. 
Therefore, I added three new path details, e.g. with a single via-point we get two entries (because there are two legs) for each detail:
```json
{
"details": {
"leg_time": [
[
0,
6,
48559
],
[
6,
10,
60719
]
],
"leg_distance": [
[
0,
6,
501.46548797983564
], …
```

Add path details for the time, distance and weight of the single legs

---

client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomProfile.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMTest.java
example/src/main/java/com/graphhopper/example/RoutingExample.java
reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceClientHCTest.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceCustomModelLMTest.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceCustomModelTest.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceTruckTest.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceTurnCostsTest.java

In the current code base there are three places where we call `CustomProfile#getCustomModel` and none of them expects the custom model to be null. Therefore we almost always need to create a custom profile like this: `new CustomProfile("profile_name").setCustomModel(new CustomModel())`. I moved this into the constructor.
In the rare cases where we use the `custom_model_files` hint (in Java code, for tests etc.) we now need to set the custom model to `null`.

Set empty custom model in custom profile constructor

---

core/src/main/java/com/graphhopper/routing/util/parsers/CarAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java

[This](https://www.openstreetmap.org/node/1306290896) is a fairly exotic example of a barrier node (`ford=yes`) within a ferry route. In this case the question arises which road environment shall be assigned. I think it should be `ferry`, because also for ways `ferry` overrules `ford`.
Btw: It seems a bit odd that there is a special road environment for `ford` but not for the other types of barriers like `gate` etc.?

Make RoadEnvironment.FERRY overrule RoadEnvironment.FORD also for node tags

---

core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java
core/src/main/java/com/graphhopper/routing/util/parsers/AbstractAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonPriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/CarAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/CarAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootPriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/WheelchairAverageSpeedParser.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMRoadEnvironmentParserTest.java

OSMRoadEnvironmentParser and the speed parsers did not use the same definition of when an OSM way is a ferry route (the road environment parser considered `ferry=no`, but the speed parsers did not). So now they use the same static method for this. 
Note that the access parsers still consider ways tagged with both `route=ferry` and `highway` as highways, while the speed parsers and the road environment parser considers these as ferries. Will fix this in a follow-up PR.

Use same definition for ferries for road environment and speed parsers

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/reader/osm/RestrictionTagParser.java
core/src/main/java/com/graphhopper/routing/DefaultWeightingFactory.java
core/src/main/java/com/graphhopper/routing/ch/CHPreparationGraph.java
core/src/main/java/com/graphhopper/routing/ev/TurnRestriction.java
core/src/main/java/com/graphhopper/routing/util/VehicleEncodedValues.java
core/src/main/java/com/graphhopper/routing/util/parsers/RestrictionSetter.java
core/src/main/java/com/graphhopper/routing/weighting/DefaultTurnCostProvider.java
core/src/main/java/com/graphhopper/routing/weighting/SpeedWeighting.java
core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/AlternativeRouteTest.java
core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/CarTagParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/RestrictionSetterTest.java
core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
tools/src/main/java/com/graphhopper/tools/Measurement.java
web-bundle/src/main/java/com/graphhopper/resources/InfoResource.java

OSM only contains data about turns being forbidden or not so it is sufficient to store this information using a boolean value instead of the decimal turn costs we used so far. On a lower level it is (and will be) still possible to store decimal turn costs per turn (or other turn cost encoded values), of course.

Use boolean turn restriction enc instead of decimal turn cost enc

---

core/src/main/java/com/graphhopper/GraphHopper.java

Fixes #2908 
Now we get an error if a custom_model_file in the custom model file directory uses the same name as one of the built-in models from the jar.

No longer allow built-in custom model file names

---

core/src/main/java/com/graphhopper/util/details/ConstantDetailsBuilder.java
web/src/test/java/com/graphhopper/application/resources/RouteResourceClientHCTest.java

Fixes #2915. This makes sure there are always N+1 leg_time/distance entries for requests with N via-points, even when some locations are duplicated. The interval of the path detail is empty for duplicate locations, because there are no edges inbetween. Here is the leg_time path detail list for the test mentioned in #2915:

Create leg_time/distance entries for duplicate via-points

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/util/DefaultVehicleTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/VehicleEncodedValues.java
core/src/main/java/com/graphhopper/routing/util/VehicleTagParsers.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikeAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikeAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/BikePriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/CarAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/CarAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/FootPriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/MountainBikeAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/MountainBikeAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/MountainBikePriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/RacingBikeAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/RacingBikeAverageSpeedParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/RacingBikePriorityParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/RoadsAccessParser.java
core/src/main/java/com/graphhopper/routing/util/parsers/RoadsAverageSpeedParser.java
core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/CarTagParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/FootTagParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/HikeCustomModelTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/RacingBikeTagParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/RoadsTagParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/TagParsingTest.java

This is leftover code of the old flag encoder approach and I don't think it has a real use case. The only thing I could think of that could be useful is using [multiple roads vehicles with different transportation modes](https://discuss.graphhopper.com/t/how-to-using-road-vehicle-for-multi-profile/8375/6) but this doesn't even work currently, because we ignore the 'name' field [here](https://github.com/graphhopper/graphhopper/blob/ddb0471520a2e9f5a6d318942c88a604edc3aedb/core/src/main/java/com/graphhopper/GraphHopper.java#L728-L735)

Remove the name property from vehicle parsers

---

core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java

While DijkstraOneToMany evaluates the timeout, it's missing the setup.

Add missing setup call

---

core/src/main/java/com/graphhopper/util/details/IntersectionValues.java
navigation/src/test/java/com/graphhopper/navigation/NavigateResponseConverterTest.java

The previous fix handled two issues: 
* Deduplicating barriers (intersections) for NavigationConverter
* Fixing Arrival and Departures (intersections) for NavigationConverter to have only an in or out link. 
What I missed is an arrival or departure intersection, deduplicating an Arrival or Departure intersection with only an in or out link.
@boldtrn can you check please ?

fix: starting at a barrier for navigation converter

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/isochrone/algorithm/JTSTriangulator.java

This PR is based on this discussion with Martin (Dr. JTS): https://github.com/locationtech/jts/issues/1121
He suggested that DelaunayTriangulationBuilder is likely the most appropriate way to build this triangulation.
i'm unsure if there are other simplifications that can be made to this class based on the changes in this PR.
I apologize for failing to add a new test, I am struggling to build a test case that captures the bug in the JTS issue above.

In JTSTriangulator, use DelaunayTriangulationBuilder instead of ConformingDelaunayTriangulator
