graphhopper/graphhopper

core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java

changed method to apply method parameter. Other option would be to remove parameter from method, but currently the method is called with the parameter throughout GraphHopper.

apply method parameter

---

core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/util/Constants.java
core/src/test/java/com/graphhopper/GraphHopperIT.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

fixed some issues about roundabout instructions

Roundabout fix

---

docs/index.md

A few more comments about the linked docs in /docs/index.md

Further documentation of the Core docs

---

web/src/main/webapp/js/main.js

Updating permalink when base layer was changed

Partially fixes 'layer not updated in URL' #266

---

android/app/build.gradle
android/app/pom.xml
android/app/src/main/java/com/graphhopper/android/MainActivity.java

Peter we published recently Mapsforge 0.5.1.
It would be good to integrate it to GraphHopper too.
I modified the Android sample where it was needed because of some API changes.

Android: advance to Mapsforge 0.5.1

---

docs/core/weighting.md

Fixed a couple parameter name mismatches in the example code for the weighting docs.

Changed var names to match those passed into methods

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MountainBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/storage/StorableProperties.java
core/src/main/java/com/graphhopper/util/PMap.java
core/src/test/java/com/graphhopper/routing/util/AbstractFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/EncodingManagerTest.java
core/src/test/java/com/graphhopper/util/PMapTest.java

This adds version numbers to all encoder classes. The numbers are stored with the graph and checked on reloading.

Flag encoder versions

---

android/app/src/main/java/com/graphhopper/android/MainActivity.java

Fix compile error in Android Sample due to #451 changes.

Android Sample: fix compile error, #451

---

docs/android/index.md

Update Android docs, #458

---

core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/PriorityWeighting.java
core/src/test/java/com/graphhopper/GraphHopperIT.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

Foot handling improvement for avoidance handling triggered by issue 463.

---

android/app/build.gradle
android/app/pom.xml
android/app/src/main/java/com/graphhopper/android/MainActivity.java

We released [Mapsforge 0.5.2](https://groups.google.com/forum/#!topic/mapsforge-dev/QnUP2BnAUrs) so let's integrate it.
- Upgrade to Mapsforge 0.5.2
- Android sample:
- Mapsforge simplified cleanup
- Semi transparent route

Mapsforge 0.5.2

---

core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java

Fixed Type in MotorcycleFlagEncoder

---

android/build.gradle

Following latest Android Studio recommendations for Gradle repositories.

Gradle: repositories improvements

---

android/app/build.gradle
android/app/pom.xml
android/app/src/main/java/com/graphhopper/android/MainActivity.java

[Mapsforge 0.6.0](https://groups.google.com/forum/#!topic/mapsforge-dev/flkbpAmZfFE)
- Multilingual maps
- Android gestures total overhaul
- API changes _(fixed imports in Sample)_
- Various improvements and bug fixes

Android Sample: advance to Mapsforge 0.6.0

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java

Increase bike priority level by one step in case of scenic=yes tag.

---

core/files/IntelliJ15GraphHopperFormatting.xml
docs/core/quickstart-from-source.md

Here is my current formatting profile for IntelliJ. Probably not everything matches exactly, but better than the default intelliJ settings.

Intelli j profile

---

docs/core/deploy.md
docs/core/quickstart-from-source.md

Added Information on how to develop using the modularized JS. Also I fixed an issue in the autocomplete documentation from yesterday.

Added JS development information

---

web/src/main/webapp/js/autocomplete.js
web/src/main/webapp/js/graphhopper/GHRequest.js
web/src/main/webapp/js/instructions.js

Add missing "translate." prefix

---

web/src/main/webapp/js/main-template.js

The Add-Button was not working, since GHInput was not found.

Added GHInput Import

---

web/src/main/java/com/graphhopper/http/GraphHopperWeb.java

1) Fix "algorithm" parameter name
2) Add "alternative_route.max_num" as a parameter on the http request

Small fixes to make alternate routes work with the web module 

---

core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java

Just a tiny amount of tidying.
I'm hoping to have a look through more of the code when I get time.
🎁

Refactor prepare contraction hierarchies

---

core/src/main/java/com/graphhopper/routing/DijkstraOneToMany.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/FastestWeighting.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/TraversalMode.java
core/src/main/java/com/graphhopper/routing/util/Weighting.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/DAType.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/storage/GraphExtension.java
core/src/main/java/com/graphhopper/storage/index/Location2IDQuadtree.java
core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
core/src/main/java/com/graphhopper/storage/index/QueryResult.java

Should all be non-breaking, very safe changes.
🎁

Non-breaking changes: correct spellings and remove redundant semi-colons

---

web/src/main/webapp/css/style.css

Avoid syntax error detection under NetBeans 8.1.

Fix of wrong comment

---

docs/core/quickstart-from-source.md

The script is actually named "lint" in package.json

Fix wrong script name

---

android/app/build.gradle

Update Android build tools to latest version.

Gradle: update Android build tools to 23.0.3

---

android/build.gradle
android/gradle.properties

- Update Gradle plugin 2.1.0
- Include `gradle.properties` for [dexing-in-process](http://developer.android.com/tools/revisions/gradle-plugin.html#revisions)

Android Sample: update Gradle

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

Add support for the vehicle tag for bicycles and foot.
Theses changes were triggered by issue #695.

Add support for bicycle:dismount.

---

config-example.properties

We forgot to adapt the example config.

Updated Config Example

---

android/app/build.gradle
android/app/src/main/java/com/graphhopper/android/MainActivity.java

We released [Mapsforge 0.6.1](https://groups.google.com/forum/#!topic/mapsforge-dev/F_uBzeJ4Thc).
Let's update GraphHopper sample with that.

Android Sample: update to Mapsforge 0.6.1

---

android/app/build.gradle

@karussell do we need to advance also Android version in pom.xml [here](https://github.com/graphhopper/graphhopper/blob/master/android/app/pom.xml#L121)?

Gradle: advance to Android 7 Nougat

---

core/src/main/java/com/graphhopper/util/FinishInstruction.java

Preparing to fix this [Issue](https://github.com/graphhopper/directions-api-java-client/issues/15)
Therefore, we need the possibility to add a name to the FinishInstruction. This method will be used [here](https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GraphHopperWeb.java#L304).

Added the possibility to add a name to the finish instruction

---

core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java

This PR adds a few utility methods to check if the edge is a tunnel or a bridge edge.

Issue #713 part 1: store tunnel and bridge tags.

---

core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

there is many roads with surface unpaved and compacted, at least in Russia
example 
https://graphhopper.com/maps/?point=58.1353%2C52.6624&point=58.219602%2C53.183345&locale=ru-RU&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale
highway=secondary with surface=unpaved
https://www.openstreetmap.org/way/418251922

adding unpaved and compacted to badSurfaceSpeedMap

---

.gitattributes

Affects only 1 file in the repository:
`/web/src/main/webapp/index.html`
Sort lines by extension.

Add *.html to extensions where we normalize line endings on checkout

---

web/src/test/webapp/spec/routeManipulationSpec.js

When running `npm run test`.
Another follow-up to Leaflet 1.0 upgrade.

Fix JavaScript tests

---

web/src/main/webapp/css/style.css

- Cursor when dragging location points should show arrows up and down, not only up, as we can reorder points both up or down
- Remove duplicate "color"
- No need to specify units for 0 something

Fix minor CSS issues

---

.travis.yml
core/src/main/java/com/graphhopper/util/Constants.java
core/src/main/java/com/graphhopper/util/Helper.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
pom.xml

I'm trying to get the jdk9 build green via ignoring some tests regarding memory mapping
First shot ... maybe it already works and/or @mprins can help :) ?
Later on we should make it working or mark those tests with annotations to ignore them as discussed [here](https://github.com/graphhopper/graphhopper/issues/701#issuecomment-251655568)

Solve mmap for jdk9

---

core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/DataFlagEncoderTest.java

This PR fixes #860 by reducing maxspeeds > 140 to 140.

Correct too large speed values

---

core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java

Sorry, should have included this in #879 ...

public access to deltaLon/Lat

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java

This change implements access issue for bicycles as discussed in #280.

Accept keys "cycleway:left" and "cycleway:right"  with "opposite" values

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java
core/src/test/java/com/graphhopper/routing/QueryGraphTest.java

This addresses issue #885.
Also needed for graphhopper/map-matching#70

Refactor unfavoring of virtual edges (#885)

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/test/java/com/graphhopper/GraphHopperAPITest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java

To test #845 better I introduced one new concurrent test. But this looks rather complicated, maybe I did something wrong.

Test concurrent graph change api while routing

---

docs/web/api-doc.md

This PR adds documentation about the exited parameter. Sorry for the weird commit history :)

Exited documentation update

---

core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

This pull request detects motorroad=yes tag in highways and fetch the speed accordingly.

parse motorroad=yes in CarFlagEncoder

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/storage/index/Location2IDFullIndex.java
core/src/main/java/com/graphhopper/storage/index/Location2IDFullWithEdgesIndex.java
core/src/main/java/com/graphhopper/storage/index/Location2IDQuadtree.java
core/src/main/java/com/graphhopper/storage/index/LocationIndex.java
core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
core/src/test/java/com/graphhopper/routing/PathTest.java

Fixes #945 
This breaks the old API but was announced earlier via deprecated.

Remove deprecated methods

---

docs/core/landmarks.md
docs/index.md

Please review and also waiting for #960 being merged ...

better landmark docs

---

android/app/build.gradle
android/app/src/main/java/com/graphhopper/android/MainActivity.java

[VTM 0.7.0](https://groups.google.com/forum/#!topic/mapsforge-dev/9T38NQrvHv4) OpenGL vector map library was released!
This PR updates Android sample with latest improvements and new render theme SVG rendering.
Fixes #882

Android: update VTM 0.7.0 OpenGL vector map library

---

core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/main/java/com/graphhopper/routing/ch/PrepareEncoder.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareEncoderTest.java

Fix CH preparation bug

---

core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java

Similar to #980 I added the Executor Service for landmarks. I also ran a brief Performance test:
Runs                    | Start LM         | End LM         | Duration LM | Took (shortest, fastest)      |
----------------------- | ------------------ | ------------------ | ----------------- | ---------- |
LM Wrapped Runnable | 11:07:14,586 | 11:14:37,499 | 7:23 min | 379,422 |
LM Runnable | 11:29:50,883 | 11:37:39,645 | 7:49 min | 377, 468 |

Added ExecutorService for Landmarks

---

core/src/test/java/com/graphhopper/routing/PathTest.java

Sorry, I forgot to reenable these tests.

Improve Instructions: Reenable tests

---

core/src/main/java/com/graphhopper/routing/Path.java

There is an issue with the ORs. We should only accept if both times either the left or the right side are true. Right now, we accept combinations like left, right or right, left.
Haven't found an issue with this yet, but it might happen.

Improve Instructions: removed a weak if

---

core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/main/java/com/graphhopper/routing/InstructionsHelper.java
core/src/main/java/com/graphhopper/routing/InstructionsSurroundingEdges.java

Overall this refactoring should increase the performance of the instruction calculation, by reducing the usage of EdgeExplorers, on the other hand I extracted some logic from the InstructionFromEdges class, see https://github.com/boldtrn/graphhopper/commit/88642b4d7d801b41e17b09b41a38bb6bfe971132.
At first I had the InstructionsSurroundingEdges class as inner class, when extracting it, I needed to create a Helper class as there is some shared functionality, used by InstructionsSurroundingEdges and InstructionFromEdges. The shared functionality is about the angle calculation and comparing street names, so no heavy lifting.
@michaz would you mind to have a look at the extract? WDYT, does it makes sense to extract this part of the code?

Refactor Instruction Generation

---

core/files/changelog.txt
web/pom.xml
web/src/main/java/com/graphhopper/http/DefaultModule.java
web/src/main/java/com/graphhopper/http/GHServer.java
web/src/main/java/com/graphhopper/http/GraphHopperModule.java
web/src/main/java/com/graphhopper/http/GraphHopperServletModule.java
web/src/main/java/com/graphhopper/http/GuiceServletConfig.java
web/src/test/java/com/graphhopper/http/BaseServletTester.java
web/src/test/java/com/graphhopper/http/SpatialRuleLookupBuilderTest.java

Furthermore I made the createGraphHopper method protected to being able using the same instance with SpatialRuleLookupBuilder

Move importOrLoad outside of Guice and use addShutdownHook

---

config-example.properties

fixes some minor spelling errors

---

docs/core/spatial-rules.md
docs/index.md

I also fixed some spelling issues and made the documentation a bit clearer in some parts.

Added a link to the SpatialRule documentation

---

web/pom.xml
web/src/main/java/com/graphhopper/http/GHServer.java

```
/* ------------------------------------------------------------ */
/**
* @param redirectWelcome
*            If true, welcome files are redirected rather than forwarded to.
*            redirection is always used if the ResourceHandler is not scoped by
*            a ContextHandler
*/
public void setRedirectWelcome(boolean redirectWelcome)
{
_resourceService.setRedirectWelcome(redirectWelcome);
}
```

Upgrade Jetty. #1041

---

core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java
core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java

Fixes #1060 
Nice to fix something just by removing code :) ... not sure why I sometimes think so circuitous and what the reasoning behind the properties storing was. Probably I wanted that you do not have to re-do the okay preparations if just one preparation failed because for world wide CH preparations can take several hours.

improve error handling for CH and LM preparation

---

core/src/main/java/com/graphhopper/routing/util/Car4WDFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java

motor vehicles should consider vehicle tags for ferries

---

android/build.gradle

Preparing for GraphHopper 0.9.0!

Android sample: update Gradle plugin

---

core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java
web/src/main/java/com/graphhopper/http/GHServer.java
web/src/test/java/com/graphhopper/http/BaseServletTester.java
web/src/test/java/com/graphhopper/http/GraphHopperLandmarksIT.java

avoid mixing CH & LM for now

---

core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java
core/src/test/java/com/graphhopper/routing/lm/LMAlgoFactoryDecoratorTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

Allow defining lm.prepare.weightings=no

---

reader-gtfs/pom.xml
reader-osm/pom.xml
reader-shp/pom.xml

https://github.com/graphhopper/graphhopper/issues/1092

Remove slf4j-log4j12 and log4j from compile/runtime scope

---

android/app/build.gradle
android/app/pom.xml
android/app/src/main/java/com/graphhopper/android/MainActivity.java
android/build.gradle

[VTM 0.8.0](https://groups.google.com/forum/#!topic/mapsforge-dev/OUVBrmBHJGs) OpenGL vector map library released!

Android: VTM 0.8.0 OpenGL vector map library

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/HikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

Fixes #1122. Fixes #1119.
I added a check for restrictions, if highway is not set. If any restrictions apply, we don't accept the way.

Check access restrictions for ways with highway==null

---

docs/core/weighting.md

I updated the weighting documentation, as the current code examples were outdated.

Updated the Weighting documentation to reflect the current state of GH

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/util/Parameters.java
core/src/main/java/com/graphhopper/util/details/EdgeIdDetails.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/main/java/com/graphhopper/util/details/StreetNameDetails.java
core/src/main/java/com/graphhopper/util/details/TimeDetails.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
web/src/main/java/com/graphhopper/http/GraphHopperServletModule.java
web/src/main/java/com/graphhopper/http/GraphHopperWeb.java
web/src/test/java/com/graphhopper/http/GraphHopperServletIT.java

Fixes #1140.
I added all PathDetails that were requested in #1140. In order to add the time, I used the Weighting. I don't especially like this, as it adds an additional dependency, but I think it's the best solution for this problem.

Add more PathDetails

---

core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/main/java/com/graphhopper/util/details/TimeDetails.java
core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

Sorry, forgot to change that in #1142 :).

TimeDetails don't need encoder.isBackward()

---

docs/core/technical.md

Fix typo in technical.md

---

client-hc/src/main/java/com/graphhopper/api/GHMatrixBatchRequester.java

@karussell there is this batchIT testBike(..) which does not work as expected anymore. Would you mind to have a brief look at it?

consider hints in batch mode

---

docs/web/api-doc.md

I added some basic information to use the path details with the API.

Added PathDetails documentation

---

core/src/main/java/com/graphhopper/storage/EdgeAccess.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/storage/AbstractGraphStorageTester.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

just some minor changes that I thought were useful when browsing the code base

some random improvements

---

core/src/main/java/com/graphhopper/util/Helper.java

Forgot to remove that import in #1194

Removed unnecessary input

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/util/Helper.java

Use android compatible way to unmap a ByteBuffer in java 9

---

config-example.properties
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/reader/dem/AbstractTiffElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/CGIARProvider.java
core/src/main/java/com/graphhopper/reader/dem/GMTEDProvider.java
core/src/main/java/com/graphhopper/reader/dem/HeightTile.java
core/src/main/java/com/graphhopper/reader/dem/MultiSourceElevationProvider.java
core/src/main/java/com/graphhopper/reader/dem/SRTMProvider.java
core/src/test/java/com/graphhopper/reader/dem/GMTEDProviderTest.java
core/src/test/java/com/graphhopper/reader/dem/HeightTileTest.java
core/src/test/java/com/graphhopper/reader/dem/MultiSourceElevationProviderTest.java

This PR is a clone of #1217. 
You can now import GMTED2010 elevation data, which has roughly a 250m resoultion. You can mix SRTM data with GMTED data by using the new MultiSourceElevationProvider by using GMTED data outside of the SRTM area.

Importing GMTED2010 elevation data and MultiSourceElevationProvider

---

android/app/build.gradle
android/app/pom.xml
android/app/proguard-rules.pro
android/app/src/main/java/com/graphhopper/android/MainActivity.java
android/build.gradle

[VTM 0.9.0](https://groups.google.com/forum/#!topic/mapsforge-dev/RRvROF866r8) OpenGL vector map library was released!

Android: VTM 0.9.0 OpenGL vector map library

---

CONTRIBUTORS.md
Dockerfile
core/files/docker-compose.yml

I've modified the Dockerfile and the docker-compose to use Docker conventions.
You now have an entrypoint in the Dockerfile and only a command in the docker-compose.yml file.
What's more, I think you should create your own docker image on docker hub (https://docs.docker.com/docker-hub/repos/#searching-for-images) and also perhaps create automatic builds (https://docs.docker.com/docker-hub/github/#github-service-hooks). I could do it, but I think you should create your own ids and organization on docker hub. I could also provide help if necessary.

Docker conventions and thoughts

---

android/app/build.gradle

[VTM 0.9.1](https://groups.google.com/forum/#!topic/mapsforge-dev/RRvROF866r8) OpenGL vector map library was released (with an important fix).

Android: VTM 0.9.1 OpenGL vector map library

---

NOTICE.md

Have a look at the TODOs, I wasn't sure at 1 or 2 places.
Fixes #1262.

Add data license table

---

docs/core/routing.md

As noted in the forum the routing.md was a bit outdated. I added some information about the Hybrid mode as well as updated the location of the clients.

Update Routing Doc

---

.travis.yml

Rollback maven version for now

---

core/src/main/java/com/graphhopper/util/PathSimplification.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

simplify also when instructions disabled

---

docs/core/quickstart-from-source.md
graphhopper.sh
web/pom.xml
web/src/main/java/com/graphhopper/http/GraphHopperDebugApplication.java

serve static content from disc instead from classpath

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

- Tests for each main flag encoder (including: FootFlagEncoderTest, CarFlagEncoderTest, BikeFlagEncoderTest)
- Added [cattle_grid](https://wiki.openstreetmap.org/wiki/Tag:barrier=cattle%20grid?uselang=en-GB) to the potential barrier lists of the main flag encoders
------
Fixes issue #1479

Accept cattle grid #1479

---

web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java

Removed redundant violation checks of maxMeter and maxSeconds in isohrone API

---

core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java

Allows using less ch weightings than loaded, fixes #1413.

---

reader-gtfs/src/main/java/com/conveyal/gtfs/GTFSFeed.java
reader-gtfs/src/main/java/com/conveyal/gtfs/error/GeneralError.java
reader-gtfs/src/main/java/com/conveyal/gtfs/model/Route.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GraphHopperGtfs.java
reader-gtfs/src/main/java/com/graphhopper/reader/gtfs/GtfsStorage.java

Don't re-open half-constructed GTFS-DBs; better logging

---

core/src/main/java/com/graphhopper/routing/QueryGraph.java
core/src/test/java/com/graphhopper/routing/QueryGraphTest.java

Fixes virtual edge way geometry in case of Position.PILLAR.

---

docs/core/eclipse-setup.md

Fix formatting of documentation

Fix formatting

---

android/app/build.gradle
android/app/pom.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

- [VTM 0.11.0](https://github.com/mapsforge/vtm) OpenGL vector map library
- Update Android build system

Android: VTM 0.11.0 OpenGL vector map library

---

docs/core/low-level-api.md
docs/core/routing.md

The constructor is private and you have to use the factory methods.

Update documentation regarding usage of EncodingManager's constructor

---

android/app/build.gradle
android/app/pom.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

- [VTM 0.11.1](https://github.com/mapsforge/vtm) OpenGL vector map library
- Update Android build system

Android: VTM 0.11.1 OpenGL vector map library

---

core/src/main/java/com/graphhopper/routing/profiles/EnumEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/UnsignedDecimalEncodedValue.java
core/src/main/java/com/graphhopper/routing/profiles/UnsignedIntEncodedValue.java

use staticHashCode to fix problems on Android but could occur elsewhere

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/test/java/com/graphhopper/routing/AStarBidirectionEdgeCHTest.java
core/src/test/java/com/graphhopper/routing/AbstractRoutingAlgorithmTester.java
core/src/test/java/com/graphhopper/routing/CHQueryWithTurnCostsTest.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionEdgeCHTest.java
core/src/test/java/com/graphhopper/routing/RandomCHRoutingTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmIT.java
core/src/test/java/com/graphhopper/routing/ch/CHTurnCostTest.java
core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java
core/src/test/java/com/graphhopper/routing/ch/NodeBasedNodeContractorTest.java
core/src/test/java/com/graphhopper/routing/ch/Path4CHTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
core/src/test/java/com/graphhopper/routing/ch/WitnessPathSearcherTest.java
core/src/test/java/com/graphhopper/routing/util/DefaultEdgeFilterTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageCHTest.java
core/src/test/java/com/graphhopper/storage/GraphHopperStorageTest.java
core/src/test/java/com/graphhopper/storage/ShortcutUnpackerTest.java
core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeCHTest.java
core/src/test/java/com/graphhopper/util/CHEdgeIteratorTest.java
core/src/test/java/com/graphhopper/util/GHUtilityTest.java
reader-osm/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
tools/src/main/java/com/graphhopper/tools/Measurement.java
tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java

Replaces GraphHopperStorage#getGraph(Class) with getCHGraph().

---

core/src/main/java/com/graphhopper/GraphHopper.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

Throw error if edge_based=true, but encoder does not support turn costs

---

api/src/main/java/com/graphhopper/util/Helper.java
core/src/main/java/com/graphhopper/storage/GHDirectory.java
core/src/main/java/com/graphhopper/storage/MMapDataAccess.java

removed cleanHack used in MMapDataAccess

---

config-example.yml
core/src/main/java/com/graphhopper/routing/profiles/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/profiles/TrackType.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParser.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParserTest.java

This pull request adds support for OSMs [tracktype](https://wiki.openstreetmap.org/wiki/Key:tracktype) key.

Tracktype parser

---

web/src/main/resources/assets/js/config/options.js
web/src/main/resources/assets/js/config/tileLayers.js

This PR adds the Kurviger Liberty mapstyle to GH Maps and removes the old Openmapsurfer tiles that are not available anymore.

Add Kurviger Liberty and remove old Openmapsurfer Tiles

---

android/app/build.gradle
android/app/pom.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

- [VTM 0.12.0](https://github.com/mapsforge/vtm) OpenGL vector map library
- Update Android build system

Android: VTM 0.12.0 OpenGL vector map library

---

docs/core/quickstart-from-source.md

see https://github.com/graphhopper/graphhopper/pull/1641

Minor changes to developer quick start

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java

Triggered by finding of user AllroadsNL in issue #280.

Improvements for bicycle use_sidepath value taggings

---

android/app/build.gradle
android/app/pom.xml
android/build.gradle

[VTM 0.13.0](https://github.com/mapsforge/vtm) OpenGL vector map library.

Android: VTM 0.13.0 OpenGL vector map library

---

graphhopper.sh

#1878 - Add example for input file

---

core/src/main/java/com/graphhopper/routing/profiles/RoadClass.java
core/src/test/java/com/graphhopper/routing/profiles/EnumEncodedValueTest.java

* added support for footway, pedestrian, [platform](https://wiki.openstreetmap.org/wiki/Tag:highway=platform) and [corridor](https://wiki.openstreetmap.org/wiki/Tag:highway=corridor)*
* avoid Exceptions in `RoadClass.find(String name)`
\* we could add support for other indoor routing attributes in the future: https://wiki.openstreetmap.org/wiki/Key:indoor

Extend RoadClass

---

core/src/main/java/com/graphhopper/storage/TurnCostStorage.java
core/src/test/java/com/graphhopper/storage/TurnCostStorageTest.java

reducing IntsRef creation should reduce GC activity a bit

avoid IntsRef recreation and simpler getter

---

benchmark/benchmark.sh
core/src/main/java/com/graphhopper/util/MiniPerfTest.java
core/src/test/java/com/graphhopper/routing/util/spatialrules/SpatialRuleLookupBuilderTest.java
tools/pom.xml
tools/src/main/java/com/graphhopper/tools/Measurement.java

This should fix the sporadically failing unittests.

Move SpatialRuleLookup benchmark into Measurement class

---

core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java

As with N, E, S, W the other directions are important for the road name

Added more compass directions

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java
reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java

Disable turn costs for LM preparation

---

.travis.yml
benchmark/benchmark.sh
tools/src/main/java/com/graphhopper/tools/Measurement.java

fixes #1961
The point check will slow down block_area a bit but it should be comparable once this is introduced.

improve Measurement for block_area

---

pom.xml

On my local machine I had memory issues with the web integration test. Strange as it disappeared after the 3rd run. Travis seems to be fine with it too.
Fixes #1558.

Upgrade to dropwizard 2.0.x

---

api/src/main/java/com/graphhopper/util/Helper.java
core/src/main/java/com/graphhopper/GraphHopper.java

This PR is opened in order to create a branch the work on graphhopper-ios https://github.com/graphhopper/graphhopper-ios/pull/47  can depend on for the time being. Please do not close the PR right now.

iOS port: remove Java Runtime specifics

---

api/src/main/java/com/graphhopper/routing/util/CustomModel.java
api/src/test/java/com/graphhopper/routing/util/CustomModelTest.java
core/src/main/java/com/graphhopper/routing/weighting/custom/BooleanToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomProfileConfig.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/custom/DecimalToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/EdgeToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/EnumToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/GeoToValueEntry.java
core/src/main/java/com/graphhopper/routing/weighting/custom/PriorityCalculator.java
core/src/main/java/com/graphhopper/routing/weighting/custom/SpeedCalculator.java
core/src/test/java/com/graphhopper/routing/weighting/CustomWeightingTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/DecimalToValueEntryTest.java
web/src/test/java/com/graphhopper/http/resources/CustomWeightingRouteResourceLMTest.java
web/src/test/resources/com/graphhopper/http/resources/cargo_bike.yml
web/src/test/resources/com/graphhopper/http/resources/truck.yml

This is for #1841.
@easbar didn't want to disturb your refactorings, so I created this branch ... please merge it when it fine for you.
One open task is to do the proper merge (or error reporting on merge), but I can do that later.

Move max_weight into priority and more refactorings

---

web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java
web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java
web/src/test/java/com/graphhopper/http/resources/IsochroneResourceTest.java

@easbar is there a reason turn_costs=false/true is not removed for isochrone too?

remove legacy turn_costs for isochrone too

---

pom.xml
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java

Make sure jersey errors are english

---

api/src/main/java/com/graphhopper/util/Helper.java
tools/src/main/java/com/graphhopper/tools/Measurement.java
web-bundle/src/main/java/com/graphhopper/http/GraphHopperBundle.java

Last one for now :)
Move two problematic functions for porting to iOS to the separate tool where it is used, only.

Move mx beans2 measurement

---

api/src/main/java/com/graphhopper/util/Parameters.java
core/src/main/java/com/graphhopper/util/details/EdgeKeyDetails.java
core/src/main/java/com/graphhopper/util/details/PathDetailsBuilderFactory.java
core/src/test/java/com/graphhopper/routing/PathTest.java

Because edge key is at least as interesting as edge id.

Provide edge key PathDetails

---

isochrone/src/main/java/com/graphhopper/isochrone/algorithm/ShortestPathTree.java
isochrone/src/test/java/com/graphhopper/isochrone/algorithm/ShortestPathTreeTest.java

Work around slow PriorityQueue.remove

---

reader-gtfs/src/main/java/com/conveyal/gtfs/GTFSFeed.java

See: https://github.com/conveyal/gtfs-lib/blob/dev/src/main/java/com/conveyal/gtfs/GTFSFeed.java

Restored the code from conveyal GTFSFeed to support interpolated stop times - Issue #2095

---

core/src/main/java/com/graphhopper/routing/Router.java

This PR resulted from this discussion: https://discuss.graphhopper.com/t/make-router-extendable/5871
This should make it a lot easier to extend the Router

Make it easier to extend Router

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java

See issue #504. Now allowing highway=bridleway with bicycle=yes for bicycles.

Allow highway=bridleway with bicycle=yes for BikeCommonFlagEncoder

---

graphhopper.sh

The name printed did not match the file used

Update default config file name in graphhopper.sh output

---

core/files/changelog.txt

See https://github.com/graphhopper/graphhopper/commit/3546c2ef8bcd74c128f6598a2b2c775e2f5c8d65#r42976520

Update changelog about maxspeed

---

core/src/main/java/com/graphhopper/reader/OSMTurnRelation.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
reader-osm/src/test/resources/com/graphhopper/reader/osm/test-restrictions.xml

This PR fixes #1302. It's really nice that this works with minimal code changes. I tested this for a few live examples and it seems to work fine.

Add no_entry to TurnRestrictions

---

core/src/main/java/com/graphhopper/util/MiniPerfTest.java
reader-osm/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
tools/src/main/java/com/graphhopper/tools/CHMeasurement.java
tools/src/main/java/com/graphhopper/tools/Measurement.java

Let's see if this could fix #2056.
(Not sure about the name `MeasurementUnit`. Maybe just `Unit` or `UnderMeasurement`?)

MiniPerfTest: no subclassing, inject lambda instead

---

README.md

* builds on recent OS versions
* fixed memory leaks: europe can be converted on a regular desktop
* IDs in the pbf are properly sorted
* properly converted road types

Update README to point to an actively maintained morituri fork

---

reader-osm/src/main/java/com/graphhopper/reader/osm/OSMInputFile.java

This PR tries to avoid the locking overhead caused by polling the LinkedBlockingQueue for each element by draining up to 1k available elements into an ArrayDeque.

Avoid frequent polling in OSMInputFile

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java
core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java

Minor refactoring for LocationIndexTree

---

core/src/main/java/com/graphhopper/routing/ev/TrackType.java
core/src/main/java/com/graphhopper/util/details/BooleanDetails.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMTrackTypeParserTest.java
web/src/test/resources/com/graphhopper/http/resources/cargo_bike.yml

Minor comment updates

---

core/src/main/java/com/graphhopper/routing/ev/EncodedValueLookup.java
core/src/main/java/com/graphhopper/routing/ev/StringEncodedValue.java
core/src/main/java/com/graphhopper/routing/ev/UnsignedIntEncodedValue.java
core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIterator.java
core/src/main/java/com/graphhopper/routing/querygraph/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/main/java/com/graphhopper/util/details/StringDetails.java
core/src/test/java/com/graphhopper/routing/ev/StringEncodedValueTest.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/WrapperGraph.java

* minor code cleanup: add generic parameters to Enum references
* add StringEncodedValue which encodes Strings based on their index within a predefined list
* StringDetails for retrieval via PathDetails

StringEncodedValues

---

reader-osm/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java

Properly decode lat/lon for DenseNodes

---

core/src/main/java/com/graphhopper/reader/osm/OSMInputFile.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfDecoder.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfReader.java
core/src/main/java/com/graphhopper/reader/osm/pbf/PbfStreamSplitter.java

do not silently ignore exceptions in PBF import

---

config-example.yml
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java

In preparation for #2273
(from production statistics it seems that speed is same or even faster compared to node-based subnetwork removal)

Always use edge-based subnetwork removal

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/RoundTripRouting.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/ViaRouting.java
core/src/main/java/com/graphhopper/routing/weighting/AvoidEdgesWeighting.java
core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java

The route calculation in Router now uses different 'Solver's depending on request. Plugging in different solvers allows modifying profile selection, weighting creation, snapping behavior and routing algorithm selection.

Restructure code in Router

---

CONTRIBUTORS.md
client-hc/src/main/java/com/graphhopper/api/GraphHopperWeb.java

Bug wrong exception type

---

docs/core/custom-models.md
docs/core/profiles.md
example/src/main/java/com/graphhopper/example/RoutingExample.java
web-bundle/src/main/resources/com/graphhopper/maps/index.html

Split custom model docs into client and server parts, update to JSON

---

core/files/changelog.txt
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCC.java
core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
core/src/test/java/com/graphhopper/routing/RoundTripRoutingTest.java
core/src/test/java/com/graphhopper/routing/subnetwork/EdgeBasedTarjanSCCTest.java
core/src/test/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworksTest.java

I reviewed #2290 again and put my suggestions into this PR. See comments inline.

Clean up PrepareRoutingSubnetwork and tests

---

pom.xml
reader-gtfs/pom.xml

Moved versions into dependencyManagement section of the parent POM

Cleanup reader-gtfs dependencies

---

web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js

This is my attempt to better integrate the custom model box in the web client. I think it 'works', but for example it kind of breaks the url history as we cannot store the custom model via the url parameters.

Make custom model box work with dragging markers, changing vehicle, adding points etc.

---

api/src/main/java/com/graphhopper/json/Statement.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomWeighting.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java

Meant as a replacement for #2307.
I tried rewriting the method so it now includes LIMIT and MULTIPLY (I hope it works as good or better than the old method).

Rewrite and fix CustomModelParser#findMaxSpeed

---

CHANGELOG.md
core/src/main/java/com/graphhopper/routing/util/NameSimilarityEdgeFilter.java
core/src/test/java/com/graphhopper/routing/util/NameSimilarityEdgeFilterTest.java

Use entire road geometry for NameSimilarityEdgeFilter

---

core/src/main/java/com/graphhopper/storage/index/InMemConstructionIndex.java
core/src/main/java/com/graphhopper/storage/index/IndexStructureInfo.java
core/src/main/java/com/graphhopper/storage/index/LineIntIndex.java
core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java

Factor out the part of LocationIndexTree that doesn't care about Graph and Edge and Snap, but is only a spatial index of integers by lines.
So it can be re-used for other purposes.

Factor out simple LineIntIndex

---

web-bundle/src/main/resources/com/graphhopper/maps/js/graphhopper/GHRequest.js
web-bundle/src/main/resources/com/graphhopper/maps/js/instructions.js
web-bundle/src/main/resources/com/graphhopper/maps/js/main-template.js
web-bundle/src/main/resources/com/graphhopper/maps/js/map.js

With this PR you can easily share GH links with your custom models

Maps: make export link working with custom model

---

web-bundle/src/main/resources/com/graphhopper/maps/isochrone/index.html
web-bundle/src/main/resources/com/graphhopper/maps/isochrone/index.js

Currently the profile string is hardcoded in the web ui. This change allows to modify it via the web UI.

Allow other profiles than car for isochrones.

---

CHANGELOG.md
api/src/main/java/com/graphhopper/ResponsePath.java
web-api/src/main/java/com/graphhopper/jackson/ResponsePathSerializer.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java

See discussion: https://github.com/graphhopper/graphhopper-maps/issues/115

Include BBox also if start and end are identical

---

CONTRIBUTORS.md
docs/web/api-doc.md

fixes #2350
> Please read [our contributing guide](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md) and note that also your contribution falls under the Apache License 2.0 as outlined there.
OK, though this one likely qualifies under "ineligible for copyright"
> Your first contribution should include a change where you add yourself to the CONTRIBUTORS.md file.
Also for such tiny ones?

make possible to run query after quickstart

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/RacingBikeFlagEncoderTest.java

Allow sac_scale=hiking for race bike, see discussion in #2357.

---

config-example.yml
core/src/main/java/com/graphhopper/routing/InstructionsOutgoingEdges.java
docs/core/spatial-rules.md
web/src/test/java/com/graphhopper/http/SpatialRulesTest.java

DataFlagEncoder was removed already for 1.0, but it is still mentioned in a few places

Remove some outdated mentions of the DataFlagEncoder

---

core/src/main/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParser.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMGetOffBikeParserTest.java

* No need to get off bike on paths
* Adding bicycle/official and bicycle/permissive for riding
Please read [our contributing guide](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md) and note that also your contribution falls under the Apache License 2.0 as outlined there.
Your first contribution should include a change where you add yourself to the CONTRIBUTORS.md file.

Refine OSMGetOffBikeParser

---

core/src/main/java/com/graphhopper/util/Constants.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/reader/osm/GraphHopperOSMTest.java
core/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/QueryRoutingCHGraphTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java
core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java
reader-gtfs/src/test/java/com/graphhopper/AnotherAgencyIT.java
reader-gtfs/src/test/java/com/graphhopper/FreeWalkIT.java
reader-gtfs/src/test/java/com/graphhopper/GraphHopperMultimodalIT.java
web-api/src/main/java/com/graphhopper/util/Helper.java
web/src/test/java/com/graphhopper/http/resources/NearestResourceTest.java
web/src/test/java/com/graphhopper/http/resources/NearestResourceWithEleTest.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceClientHCTest.java
web/src/test/java/com/graphhopper/http/resources/RouteResourceTest.java
web/src/test/java/com/graphhopper/http/resources/SPTResourceTest.java

Improve coordinate precision

---

core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java
core/src/test/java/com/graphhopper/routing/util/CarFlagEncoderTest.java
core/src/test/java/com/graphhopper/routing/util/FootFlagEncoderTest.java

introduce barrier=yes

---

core/src/main/java/com/graphhopper/routing/HeadingResolver.java
core/src/main/java/com/graphhopper/routing/util/HeadingEdgeFilter.java
core/src/test/java/com/graphhopper/GraphHopperTest.java

this is my suggestion for: https://github.com/graphhopper/graphhopper/pull/2411#discussion_r719595233

only calc heading of geometry first

---

.travis.yml
core/src/main/java/com/graphhopper/util/TranslationMap.java
core/src/test/java/com/graphhopper/util/TranslationMapTest.java

Locales changed in JDK17:
https://www.oracle.com/java/technologies/javase/jdk17-suported-locales.html

use jdk17 ga and jdk18 ea

---

core/src/main/java/com/graphhopper/reader/osm/OSMReader.java

Fixes #2467
@cosmin-petrescu i added you as co-author

Use a point along the edge geometry to determine areas

---

core/src/main/java/com/graphhopper/reader/osm/OSMReader.java

As discussed with @easbar in https://github.com/graphhopper/graphhopper/issues/2472#issuecomment-974087575

Use geometric center to lookup areas for ways with only two points

---

core/src/main/java/com/graphhopper/GraphHopper.java
tools/src/main/java/com/graphhopper/tools/Measurement.java

Remove the ch.prepare.done flag and separate CH and LM profile versions

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/ch/CHPreparationGraph.java
core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java
core/src/main/java/com/graphhopper/routing/lm/PrepareLandmarks.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractAdjustedWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/DefaultTurnCostProvider.java
core/src/main/java/com/graphhopper/routing/weighting/QueryGraphWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/ShortestWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/Weighting.java
core/src/main/java/com/graphhopper/storage/RoutingCHEdgeIteratorStateImpl.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/test/java/com/graphhopper/routing/DirectedRoutingTest.java
core/src/test/java/com/graphhopper/routing/RandomizedRoutingTest.java
core/src/test/java/com/graphhopper/routing/RoutingAlgorithmTest.java
core/src/test/java/com/graphhopper/routing/TrafficChangeWithNodeOrderingReusingTest.java
core/src/test/java/com/graphhopper/routing/lm/LMApproximatorTest.java
core/src/test/java/com/graphhopper/routing/lm/LMIssueTest.java
core/src/test/java/com/graphhopper/routing/lm/LMPreparationHandlerTest.java
core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/GraphExplorer.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterFreeWalkImpl.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouterImpl.java
reader-gtfs/src/main/java/com/graphhopper/gtfs/TripFromLabel.java

Fixes #2548. I managed to do this without #1835 by adding a new method to Weighting that returns true if an edge is blocked (but false does not mean that the weight is actually finite).

Remove Weighting#getFlagEncoder

---

.travis.yml

The install-sdk.sh script is no longer maintained. See also discussion: https://travis-ci.community/t/update-install-jdk-sh-with-the-new-revision/12761/7

use sdkman and switch to most recent JDK

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/weighting/custom/ExpressionVisitor.java
core/src/test/java/com/graphhopper/routing/weighting/custom/ExpressionVisitorTest.java

minor cleanup

---

web-bundle/pom.xml

Use more recent node/npm versions to fix the build

---

core/src/main/java/com/graphhopper/util/StopWatch.java
web-api/src/main/java/com/graphhopper/jackson/ResponsePathSerializer.java
web-bundle/src/main/java/com/graphhopper/resources/MapMatchingResource.java
web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java

Before, took for the route resource was given in millis and for the map matching it was in seconds. This PR fixes this inconsistency.

Fix inconsistent took

---

core/src/main/java/com/graphhopper/routing/ev/DecimalEncodedValue.java
core/src/main/java/com/graphhopper/routing/ev/DecimalEncodedValueImpl.java
core/src/main/java/com/graphhopper/routing/ev/EnumEncodedValue.java
core/src/main/java/com/graphhopper/routing/ev/IntEncodedValue.java
core/src/main/java/com/graphhopper/routing/ev/IntEncodedValueImpl.java
core/src/main/java/com/graphhopper/routing/ev/SimpleBooleanEncodedValue.java
core/src/main/java/com/graphhopper/routing/ev/StringEncodedValue.java
core/src/main/java/com/graphhopper/routing/util/parsers/helpers/OSMValueExtractor.java
core/src/main/java/com/graphhopper/routing/weighting/CurvatureWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java
core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
core/src/main/java/com/graphhopper/routing/weighting/custom/ValueExpressionVisitor.java
core/src/main/java/com/graphhopper/util/Constants.java
core/src/test/java/com/graphhopper/routing/ev/DecimalEncodedValueImplTest.java
core/src/test/java/com/graphhopper/routing/ev/EncodedValueSerializerTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxAxleLoadParserTest.java
core/src/test/java/com/graphhopper/routing/util/parsers/OSMMaxWeightParserTest.java

Following #2614 and our discussion @karussell

Rename getMin/MaxInt -> getMin/MaxStorableInt, getMaxSetValueOrMax -> getMaxOrMaxStorable

---

core/src/main/java/com/graphhopper/routing/util/DefaultFlagEncoderFactory.java
core/src/main/java/com/graphhopper/routing/util/FlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/VehicleEncodedValues.java
core/src/test/java/com/graphhopper/routing/DijkstraBidirectionCHTest.java
core/src/test/java/com/graphhopper/routing/PathTest.java
core/src/test/java/com/graphhopper/routing/PriorityRoutingTest.java
core/src/test/java/com/graphhopper/routing/util/FootTagParserTest.java
core/src/test/java/com/graphhopper/routing/weighting/FastestWeightingTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomModelParserTest.java
core/src/test/java/com/graphhopper/routing/weighting/custom/CustomWeightingTest.java
core/src/test/java/com/graphhopper/storage/index/LocationIndexTreeTest.java

Since #2614 it was not really used in production code anymore, but here it is actually removed. All these changes were also part of #2611, but I thought it makes sense to do this separately here, so there is less to deal with in #2611

Remove FlagEncoder#getMaxSpeed()

---

web-bundle/src/main/java/com/graphhopper/http/GraphHopperManaged.java

This might hopefully save time for future users, who are trying to load a custom file with the custom object option.
I relinquish the addition to CONTRIBUTORS.md, since this is a minor edit.

Add hint to exception error message

---

core/src/main/java/com/graphhopper/routing/ev/Crossing.java
core/src/main/java/com/graphhopper/routing/ev/DefaultEncodedValueFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/DefaultTagParserFactory.java
core/src/main/java/com/graphhopper/routing/util/parsers/OSMCrossingParser.java

Make it possible to avoid railroad and other crossings. (and use this in path details)
Requires: #2705

add crossing EV

---

core/src/main/java/com/graphhopper/routing/RoundTripRouting.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/util/PathMerger.java
core/src/main/java/com/graphhopper/util/PathSimplification.java
core/src/test/java/com/graphhopper/GraphHopperTest.java
core/src/test/java/com/graphhopper/util/PathSimplificationTest.java
web-api/src/main/java/com/graphhopper/ResponsePath.java

Make sure waypoints are not removed during path simplification

---

tools/src/main/java/com/graphhopper/ui/MiniGraphUI.java

The MiniGraphUI was broken, this change makes it working again.

Make the MiniGraphUI working again.

---

core/src/main/java/com/graphhopper/routing/ch/CHPreparationHandler.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java
core/src/main/java/com/graphhopper/routing/subnetwork/PrepareRoutingSubnetworks.java
core/src/main/java/com/graphhopper/routing/util/RoadDensityCalculator.java
core/src/main/java/com/graphhopper/util/GHUtility.java

see https://github.com/graphhopper/graphhopper/pull/2828#issuecomment-1566139538

Use ForkJoinPool for concurrent processing

---

.github/workflows/remove-old-artifacts.yml

For cleaning up the old packages, a few projects to try out if the work as expected, as the first one did not.

Github packages cleanup try

---

.github/workflows/remove-old-artifacts.yml

Try another action, as the previous [did not work](https://github.com/graphhopper/graphhopper/actions/runs/6044932485/job/16404237821).

Use a different action

---

core/src/main/java/com/graphhopper/reader/osm/OSMReader.java
core/src/main/java/com/graphhopper/routing/util/parsers/RestrictionSetter.java
core/src/test/java/com/graphhopper/routing/util/parsers/RestrictionSetterTest.java

Ignore via-way restrictions that share the same via-way in the same direction
